### ISSUE TITLE
SAML POST Binding Support in AuthNRequest

### ISSUE THREAD

**Issue by d3mcfadden** [onelogin/ruby-saml#124]
This is more of a general question on how you would handle POST binding to the provider with ruby-saml. I see in the docs the Redirect binding is clearly supported and documented:

```
def init
  request = OneLogin::RubySaml::Authrequest.new
  redirect_to(request.create(saml_settings))
end
```

I have a need to support the POST binding support and have written some code to do that. There is not anything to currently do this in this lib right?

**Comment by gmontard** [comment]
Hello,

We have a customer that do not accept GET params but only POST.
This would be helpful to have a simple way to chose the format to send the AuthNRequest.

Thanks.

**Comment by akshah123** [comment]
We also ran into this problem where IDP only supports POST for AuthNRequest.  Was anyone able to setup a workaround for this?

**Comment by lisadu** [comment]
Internet Explorer only supports URL length up to 2083, so a signed auth request will not work on IE via GET.

**Comment by lisadu** [comment]
We are able to do POST. 

In your controller, setup parameters for the auth form post:
```
saml_request = OneLogin::RubySaml::Authrequest.new
@post_params = saml_request.create_params(saml_settings, 'RelayState' => params[:id])
@login_url   = saml_settings.idp_sso_target_url
render :show
```

In your view, create a hidden form and JavaScript submit (example in HAML):
```
:javascript
  document.addEventListener("DOMContentLoaded", function(event) {
    document.getElementById("saml-form").submit();
  });

- form_tag @login_url, :method => :post, :id => "saml-form" do
  - @post_params.each do |key, value|
    = hidden_field_tag key, value
```

**Comment by pitbulk** [comment]
In HTTP-POST binding the Signatures are embedded, if you need to support that this solution does not work.

At SAML specification: http://docs.oasis-open.org/security/saml/v2.0/saml-conformance-2.0-os.pdf
you can see that in Web SSO, support  <AuthnRequest>  HTTP redirect is a MUST.
