### ISSUE TITLE
Compatibility with Rails 2.3?

### ISSUE THREAD

**Issue by pbraswell** [onelogin/ruby-saml#149]
Hi,
I'm trying to integrate this gem with a very old Rails 2.3 application that needs SAML integration.  Is this gem compatible with RoR 2.3 and Ruby 1.8.7?

I'm using Gem / Bundler, I've included this gem.  Bundle install works ok but when I hit:
http://localhost:8980/saml/init, I get the following Passenger error:

no such file to load -- onelogin/saml

Any ideas on what I might be doing wrong?

TIA,
Peter

**Comment by Lordnibbler** [comment]
@pbraswell I'm going to close this issue for now, please feel free to comment if you need our assistance in the future.
