### ISSUE TITLE
Can ruby-saml deal with PingFederate's SSO ?

### ISSUE THREAD

**Issue by googya** [onelogin/ruby-saml#172]
THIS IS NOT A ISSUE! 

Can ruby-saml deal with PingFederate's SSO ?  Or is there any method to sovle the problem?

**Comment by buffym** [comment]
Sorry for the delayed response - no, I never got it working. Due to time constraints, I ended up using https://github.com/digidentity/libsaml for encrypted assertions. Still using ruby-saml for other parts of SSO in our app though.

**Comment by googya** [comment]
@pitbulk 👍

**Comment by kwent** [comment]
Same issue here getting invalid signature. What PingFederate is doing differently than other IdP provider ?
