### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by liamnoone** [onelogin/ruby-saml#177]
Is there a timeline or plan for the next release of RubySaml? There hasn't been a release since 0.8.1 in February, and it is missing some key functionality, like security Settings and a metadata fetcher.

While using the `:github` directive in a Gemfile works, it isn't a solution for everyone, and a release bump that's easilly fetched from `gem` would be preferred, at least for me.

Thank you for the great gem, though.

**Comment by Lordnibbler** [comment]
@liamnoone ruby-saml 0.8.2 and 0.9 were released today!  0.8.2 fixes a security vulnerability, and 0.9 contains all pull requests from Feb 2014 to present day.

https://rubygems.org/gems/ruby-saml/versions/0.8.2
https://rubygems.org/gems/ruby-saml/versions/0.9
