### ISSUE TITLE
chdir makes code non-thread safe

### ISSUE THREAD

**Issue by draganm** [onelogin/ruby-saml#180]
Hi, while debugging my own code, stumbled over this in saml_message.rb:

      Dir.chdir(File.expand_path(File.join(File.dirname(__FILE__), '..', '..', 'schemas'))) do
          @schema = Nokogiri::XML::Schema(IO.read('saml-schema-protocol-2.0.xsd'))
          @xml = Nokogiri::XML(document.to_s)
       end

In a single threaded environment this is not an issue, but when there are more parallel threads running, there is a time window when the current working directory is changed for all threads. That could lead to random production failures on Rails using Puma for example ...

**Comment by pitbulk** [comment]
What alternative you suggest?

**Comment by draganm** [comment]
This at least eliminates chdir at run-time - it only does chdir once when .rb files are required. Should also improve performance since it eliminates disk IO at validation time.

https://github.com/onelogin/ruby-saml/pull/181

**Comment by phlipper** [comment]
This is resolved as of c8deef880b7657e34b241a17478ecb49aa21ef8f
