### ISSUE TITLE
Need to update README for encryption key settings

### ISSUE THREAD

**Issue by shyam-habarakada** [onelogin/ruby-saml#186]
### This is regarding the current `decrypt` branch

I have gotten a version of what is the decrypt branch to work against ADFS 2.0 as an IdP. However, the process I had to go through to get it working was a lot of trial and error and reading through commits and source in that branch—The README did not help much.

This issue is to determine what to add to the README so I can send in a PR.

In my current setup, I am setting `settings.idp_cert`, `settings.certificate` and `settings.private_key`. These last two values are the public key I send to the IdP for encrypting the assertion in the `SAMLResponse` and my private key for decrypting the encrypted assertion, respectively.

The `settings.certificate` I assign however is exposed as a `signing` certificate in metadata XML. Shouldn't that be an `encryption` certificate instead?

In the tests that added around encryption, there is reference to both signing and encryption as well. See 86852424fcad8f9e22de1e0a1d534b4bdfc2fd22 

Shouldn't we support separate certificates for signing vs encryption?

@pitbulk since you are currently owning the `decrypt` branch, can you please comment?

Thanks

**Comment by shyam-habarakada** [comment]
@buffym would love your input on this as well.

**Comment by pitbulk** [comment]
Hi @shyam-habarakada,

I know that the standard let you use different private_key/cert for signing and encrypting.
My experience in SAML project says to me that 99% of people use the same thing for both method.

My main goal when implementing the OneLogin's SAML Toolkits was to keep the toolkit simple and cover all the main scenarios. We already have complex solutions with complex settings and I'm trying to avoid that philosophy.

I'm agree with you that when adding that decrypt method, I will need to update the Readme and reference that the key/cert will works for both sign and encrypt.

And maybe later, if someone that really need to use different keys/certs for that I can explain him how extend the toolkit for support that, but I want to avoid adding more complexity to the settings tp cover the 1% of the cases.

Thanks you for supporting the ruby-saml toolkit and be an active contributor ;)

**Comment by buffym** [comment]
Due to time constraints on the project I am working on, I ended up doing encrypted assertions with a different gem. I was planning on taking a look back at this one once this branch was updated and merged. For what it's worth, I agree, w/ @pitbulk regarding signing/encryption keys; every case I've seen, they are the same.

**Comment by shyam-habarakada** [comment]
I am seeing customers that have different certs, although that is not directly impacting us. As an SP, I can chose to use the same for both signing and encrypting.

In the README it will be good to explain the use cases for the various key and cert and fingerprint options.

I also noticed [this line of code](https://github.com/onelogin/ruby-saml/blob/decrypt/lib/onelogin/ruby-saml/authrequest.rb#L42), which appears to point to another set of `settings.security[ .. ]` values that I did not notice in the docs.

@buffym what was the gem you used?

**Comment by pitbulk** [comment]
https://github.com/onelogin/ruby-saml/blob/b9cff234cc87c37cce66c4ff326a85686bb49c62/lib/onelogin/ruby-saml/settings.rb#L104

Yes, we may update the README.

**Comment by buffym** [comment]
@shyam-habarakada I used https://github.com/digidentity/libsaml for encrypted assertions.

**Comment by pitbulk** [comment]
I read the documentation and related to [those lines that you commented](https://github.com/onelogin/ruby-saml/blob/decrypt/lib/onelogin/ruby-saml/authrequest.rb#L42), there is a signing section that describes how it works: https://github.com/onelogin/ruby-saml/blob/decrypt/README.md#signing

After merge the encryption support, I will rebuild signature/encryption documentation from the Readme in order to clarify it.
