### ISSUE TITLE
issuer set to request.host in the README

### ISSUE THREAD

**Issue by buffym** [onelogin/ruby-saml#187]
In the README examples, issuer/relaying party is set to request.host. While this does work, I came at this gem as a SAML newbie. After much pulling of hair, I have learned that the issuer should most probably be a URL, and not just the host. Once you have clients setup who check the issuer, you can't change it, and some IdP's that I've worked with don't like a non-URL issuer/relaying party. I used request.host when starting with SAML, based on the example in the readme. I'm not sure the best thing to update this with, but I'd recommend something like 'https://www.example.com/sso/metdata', meaning making the issuer the path to the metadata, or something along those lines, so new folks don't run into the same issues.

**Comment by pitbulk** [comment]
Yes, I always follow this practice, is not a must but is high recommended.
Noted. I will mention that on the documentation

**Comment by buffym** [comment]
Thanks.
