### ISSUE TITLE
Release version 0.9.0 instead of version 0.9

### ISSUE THREAD

**Issue by TJM** [onelogin/ruby-saml#188]
Just curious why the most recent release was v 0.9?

I am not sure whether it breaks anything, but it seems like its customary to put x.y.z even if the z=0 :)

~tommy

**Comment by phlipper** [comment]
:+1:

**Comment by Lordnibbler** [comment]
@TJM @phlipper we're about to release v0.9.1, so I will yank v0.9. It was just a simple mistake, don't think its worth re-releasing at this point.

**Comment by phlipper** [comment]
@Lordnibbler thanks

**Comment by TJM** [comment]
sounds good! thanks.

**Comment by Lordnibbler** [comment]
Closing via:

https://github.com/onelogin/ruby-saml/releases/tag/v0.9.1
https://rubygems.org/gems/ruby-saml/versions/0.9.1
