### ISSUE TITLE
Errors when deploying using jruby on Tomcat

### ISSUE THREAD

**Issue by TJM** [onelogin/ruby-saml#189]
We got the following errors in catalina.out on a Tomcat server when deploying a "jruby" rails app using this gem.

Here is the error output:

```
/usr/share/tomcat7/webapps/ROOT/WEB-INF/gems/gems/bundler-1.7.12/lib/bundler/shared_helpers.rb:3:in `require': no such file to load -- rubygems (LoadError)
                from /usr/share/tomcat7/webapps/ROOT/WEB-INF/gems/gems/bundler-1.7.12/lib/bundler/shared_helpers.rb:3
                from /usr/share/tomcat7/webapps/ROOT/WEB-INF/gems/gems/bundler-1.7.12/lib/bundler/setup.rb:1:in `require'
                from /usr/share/tomcat7/webapps/ROOT/WEB-INF/gems/gems/bundler-1.7.12/lib/bundler/setup.rb:1

no ruby in PATH/CONFIG
```

Based on https://gist.github.com/kitplummer/1270732 .. we think it may have something to do with systemu, which is indirectly used by ruby-saml:

```
ruby-saml -> uuid -> macaddr -> systemu
```

Has anyone else experienced this? Has anyone else made this work in jruby, deployed in a WAR file to a Tomcat app server?

Thanks in advance,
Tommy

**Comment by pitbulk** [comment]
If you experienced problems with uuid, 
take a look on this PR and use  the SecureRandom library instead:
https://github.com/onelogin/ruby-saml/pull/206

**Comment by TJM** [comment]
Does it work in jRuby otherwise? Is that just "noise" or is it a failure?
