### ISSUE TITLE
(Quesiton) SP-Initiated Single Logout

### ISSUE THREAD

**Issue by yijia-zhan** [onelogin/ruby-saml#202]
I have been testing the gem with the **OneLogin SAML Test (IdP w/ attr w/ sign response)** app in OneLogin. I was able to get SSO and IdP-Initiated SLO working. However, there seems to be some issues with for SP-Initiated SLO:

Step-1: I send a `OneLogin::RubySaml::Logoutrequest` to IdP (from `initiate_sp_slo_request `). 

For Step-2, for the logout request that I sent in Step-1, instead of receiving a **SAMLResponse** `<domain>/saml/logout?SAMLResponse=xxx` (hits `process_sp_slo_response`) from IdP, I always received a **SAMLRequest** `<domain>/saml/logout?SAMLRequest=xxx` (hits `process_idp_slo_request`)

```ruby
# in service_provider_controller.rb

def initiate_sp_slo_request; end

def process_sp_slo_response; end

def process_idp_slo_request; end
```
But if I manually fail the `process_idp_slo_request` method call, and then initiate the SP-SLO request again, I will be able to get a **SAMLResponse** and it will hit `process_sp_slo_response`. 

I ran into this issue in my own app, but I then tested it in the [ruby-saml-examle](https://github.com/onelogin/ruby-saml-example) app and got the same behavior. 

Is there anything I did wrong? Could you share the logic on how the OneLogin IDP side handles a `OneLogin::RubySaml::Logoutrequest`? Thanks!

**Comment by pitbulk** [comment]
Hi @yijia-zhan, I will review this use case on Monday. What ruby-saml and ruby-saml-example version are you using?

**Comment by yijia-zhan** [comment]
Thanks @pitbulk. I am using latest master of `ruby-saml-example` and 0.9.1 for `ruby-saml`

**Comment by pitbulk** [comment]
Sorry for the delay, I hope to review that soon.

**Comment by pitbulk** [comment]
Working on that issue

**Comment by pitbulk** [comment]
@yijia-zhan There is a problem with the connector (OL side). We will solve that issue.

**Comment by yijia-zhan** [comment]
@pitbulk Thanks for the update!

**Comment by numsweb** [comment]
I am having this (or a similar) issue with the SLO (was using 0.8.1 but upgraded to 0.9.1 with the same results). I am sending the logout request to : 
LogoutRequest Destination='https://idp.ref.gfipm.net/idp/profile/SAML2/Redirect/SSO' 

and the response I get from their website is an error page that says: 


ERROR

An error occurred while processing your request. Please contact your helpdesk or user ID office for assistance.

This service requires cookies. Please ensure that they are enabled and try your going back to your desired resource and trying to login again.

Use of your browser's back button may cause specific errors that can be resolved by going back to your desired resource and trying to login again.

If you think you were sent here in error, please contact technical support

**Comment by numsweb** [comment]
here is the logout_request that gets generated, if that helps:

Created SLO Logout Request: <samlp:LogoutRequest Destination='https://idp.ref.gfipm.net/idp/profile/SAML2/Redirect/SSO' ID='_e543ede0-c052-0132-2c62-3c15c2de9eba' IssueInstant='2015-04-08T19:26:45Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:3000/saml/metadata</saml:Issuer><saml:NameID Format='urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'>48</saml:NameID></samlp:LogoutRequest>
"https://idp.ref.gfipm.net/idp/profile/SAML2/Redirect/SSO?SAMLRequest=fZHBasMwEER%2FxTedZMmyHRIRGwqhEEhbSEoPvRRVXicCW3K1a%2Bjn10p6CD30ItDyZjSz2qIZh0kfwjnMdISvGZCy3XI4b8gF37AL0YRaCNdNeYQ%2BP%2FduGnMPlCZiiqF3A4jTw9NBiSN0LoIlcTq9sGy%2Fa9gH1FUJHUhuZa24LErFlV0pXtqitqqDDXyaBUWcYe%2BRjKeGKVnUXFZcrl%2BLjVYrXdXvLHuDiNdEKpcs%2Bx4Hjzqlb9gcvQ4GHWpvRkBNVqc8egG1QYSYmtxLpv81SykKNgys3SZaX9PFNm1iWcQQrBkuAUmXUkqRCDECmc6Q2Yp7wU39vPjvd9ljiKOh%2Fx9OE9fx%2ForqKRVGAk%2Bsrda%2F1je39nb783HtDw%3D%3D&RelayState=http%3A%2F%2Flocalhost%3A3000%2Fsaml_login"

**Comment by pitbulk** [comment]
This error was fixed in the OneLogin service
