### ISSUE TITLE
Pure ruby support?

### ISSUE THREAD

**Issue by rafaelgonzalez** [onelogin/ruby-saml#203]
Can this be used with pure ruby? Or am I doing something wrong?

I managed to have it working with Rails, but not with ruby only.

All the following steps are reproductible in Rails (including the requirement failure) but for the last one.

**Installation went ok**

```
$ gem install ruby-saml
Fetching: ruby-saml-0.9.1.gem (100%)
Successfully installed ruby-saml-0.9.1
Parsing documentation for ruby-saml-0.9.1
Installing ri documentation for ruby-saml-0.9.1
Done installing documentation for ruby-saml after 1 seconds
1 gem installed
```

**Requirement described in [README.md](https://github.com/onelogin/ruby-saml/blob/269694335d60ca77d53ce44704421916afbe3f63/README.md#getting-started) did not work**

```
$ irb
2.1.5 :001 > require 'onelogin/ruby-saml'
LoadError: cannot load such file -- onelogin/ruby-saml
	from /Users/rafaelgonzalez/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rafaelgonzalez/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from (irb):1
	from /Users/rafaelgonzalez/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**So instead I tried**

```
2.1.5 :002 > require 'ruby-saml'
 => true
```

**Now, following the [usage example](https://github.com/onelogin/ruby-saml/blob/269694335d60ca77d53ce44704421916afbe3f63/README.md#metadata-based-configuration), it fails**

```
2.1.5 :003 > idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new
 => #<OneLogin::RubySaml::IdpMetadataParser:0x007f7f6c35a780> 
2.1.5 :004 > settings = idp_metadata_parser.parse_remote("https://my-tsta.unimelb.edu.au/fed/idp/metadata")
NameError: uninitialized constant OneLogin::RubySaml::IdpMetadataParser::Net
	from /Users/rafaelgonzalez/.rvm/gems/ruby-2.1.5/gems/ruby-saml-0.9.1/lib/onelogin/ruby-saml/idp_metadata_parser.rb:45:in `get_idp_metadata'
	from /Users/rafaelgonzalez/.rvm/gems/ruby-2.1.5/gems/ruby-saml-0.9.1/lib/onelogin/ruby-saml/idp_metadata_parser.rb:20:in `parse_remote'
	from (irb):4
	from /Users/rafaelgonzalez/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by rafaelgonzalez** [comment]
Ok, this is simply resolved by requiring `net/http`. I would have expected the gem to do it.

**Comment by Lordnibbler** [comment]
Hey @rafaelgonzalez -- would you be willing to put together a PR to resolve this issue both for ruby and rails? Thanks for taking the time to look into it!

**Comment by rafaelgonzalez** [comment]
Sure, I'll try and get around it some time this week.

**Comment by pitbulk** [comment]
Thanks

**Comment by rafaelgonzalez** [comment]
I created a PR for the `net/http` issue.

Do you want me to make another PR to update the requirement statements I mentioned here as well?

**Comment by rafaelgonzalez** [comment]
I created another PR to reflect the requirement instructions in the README. #205

**Comment by Lordnibbler** [comment]
fixed via https://github.com/onelogin/ruby-saml/pull/204

**Comment by rafaelgonzalez** [comment]
Ah right, forgot to close it! Thanks
