### ISSUE TITLE
sign_document creates invalid SAML payload

### ISSUE THREAD

**Issue by bwillis** [onelogin/ruby-saml#209]
I'm trying to do some integration testing with SAML and am attempting to use XmlSecurity::Document to construct a SAML response. I'm using sign_document to ensure the payload contains the correct `ds:Signature`, but when I attempt to validate it is invalid because the signature contains an invalid attribute `InclusiveNamespaces`. Steps I am performing:

```ruby
document = XMLSecurity::Document.new("<Valid unsigned SAML Response>")
document.sign_document(<saml_key>, <saml_cert>)
saml_response = OneLogin::RubySaml::Response.new(document.to_s)
saml_response.validate!
```
The validation exception is:
```
OneLogin::RubySaml::ValidationError: Element '{http://www.w3.org/2000/09/xmldsig#}InclusiveNamespaces': This element is not expected. Expected is ( {http://www.w3.org/2000/09/xmldsig#}Transform ).
```

As far as I can tell, the http://www.w3.org/2000/09/xmldsig does not allow `InclusiveNamespaces` which is being added https://github.com/onelogin/ruby-saml/blob/d1364717ec865e988eaec2f9d202d6da60f160ff/lib/xml_security.rb#L114. 

Can someone help me understand this?

**Comment by pitbulk** [comment]
Can you paste the SAML Response that you are trying to validate?
What version of the ruby-saml are you using?

**Comment by bwillis** [comment]
ruby-saml-0.9.1

Sample SAML Response:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<samlp:Response Destination='{recipient}' ID='R6fa6c6bfb42798aa6d2893740f1e8d0fc361ac23' InResponseTo='_36387b60-af58-0132-6be9-6c4008ad82d2' IssueInstant='2015-03-18T04:50:24Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'>
  <saml:Issuer>https://app.onelogin.com/saml/metadata/433789</saml:Issuer>
  <samlp:Status>
    <samlp:StatusCode Value='urn:oasis:names:tc:SAML:2.0:status:Success'/>
  </samlp:Status>
  <saml:Assertion ID='pfxcb6907fc-cd01-59eb-a50f-513689085a71' IssueInstant='2015-03-18T04:50:24Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <saml:Issuer>https://app.onelogin.com/saml/metadata/433789</saml:Issuer>
    <saml:Subject>
      <saml:NameID Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'>jane.doe@example.com</saml:NameID>
      <saml:SubjectConfirmation Method='urn:oasis:names:tc:SAML:2.0:cm:bearer'>
        <saml:SubjectConfirmationData InResponseTo='_36387b60-af58-0132-6be9-6c4008ad82d2' NotOnOrAfter='2015-03-19T17:57:12Z' Recipient='{recipient}'/>
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore='2015-03-18T04:47:24Z' NotOnOrAfter='2015-03-19T17:57:12Z'>
      <saml:AudienceRestriction>
        <saml:Audience>{audience}</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AuthnStatement AuthnInstant='2015-03-18T04:50:23Z' SessionIndex='_f4610090-af35-0132-899e-38ca3a662f1c' SessionNotOnOrAfter='2015-03-19T04:50:24Z'>
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
    <saml:AttributeStatement>
      <saml:Attribute Name='User.email' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'>
        <saml:AttributeValue xsi:type='xs:string' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>jane.doe@example.com</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name='User.FirstName' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'>
        <saml:AttributeValue xsi:type='xs:string' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>Jane</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name='User.LastName' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'>
        <saml:AttributeValue xsi:type='xs:string' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>Doe</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name='PersonImmutableID' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'>
        <saml:AttributeValue xsi:type='xs:string' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'/>
      </saml:Attribute>
      <saml:Attribute Name='memberOf' NameFormat='urn:oasis:names:tc:SAML:2.0:attrname-format:basic'>
        <saml:AttributeValue xsi:type='xs:string' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'/>
      </saml:Attribute>
    </saml:AttributeStatement>
  </saml:Assertion>
</samlp:Response>
```

**Comment by pitbulk** [comment]
Hi @bwillis, I have to say that this library is used to support SAML Service Provider, so adding embed signature to a SAML Response is out of scope.

In your example you build the XMLSecurity object from an string, but we never used XMLSecurity library in this way, for example review the [create_authentication_xml_doc method](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb) how we construct the document.

If you are looking for IdP functionality, take a look on [ruby-saml-idp](https://github.com/lawrencepit/ruby-saml-idp) for example.

Also If you are just playing with SAML Responses, take a look on samltool.com where you will be able to sign, validate, encrypt, decrypt, encode, decode.

**Comment by bwillis** [comment]
> so adding embed signature to a SAML Response is out of scope
That's totally fine, but I wouldn't get hung up on the fact I'm using a SAML response to test with here. If you run the valid_saml? against `create_logout_response_xml_doc` it fails in the same manner.

> P.S Notice that sign_document expects to be able to read the uuid attribute
Thanks I did catch that eventually :)

**Comment by pitbulk** [comment]
I will fix the uuid issue

**Comment by pitbulk** [comment]
I will keep this issue open, we working on saml validations, encryption and some improvements, but after that I will review that.

**Comment by bwillis** [comment]
Nice, thanks for the uuid fix, I think that'll make things a little easier.

In order to fix this locally I removed the inserting of InclusiveNamespaces node in the sign_document method, but without understanding why it's there I'm a little worried to just drop it.

**Comment by pitbulk** [comment]
The namespace of InclusiveNamespaces is not ds, is ec ==>http://www.w3.org/2001/10/xml-exc-c14n#

Fixing that.

**Comment by pitbulk** [comment]
I applied this change, but after that, some test are failing

```
--- a/lib/xml_security.rb
+++ b/lib/xml_security.rb
@@ -116,8 +116,8 @@ module XMLSecurity
       # Add Transforms
       transforms_element = reference_element.add_element("ds:Transforms")
       transforms_element.add_element("ds:Transform", {"Algorithm" => ENVELOPED_SIG})
-      transforms_element.add_element("ds:Transform", {"Algorithm" => C14N})
-      transforms_element.add_element("ds:InclusiveNamespaces", {"xmlns" => C14N, "PrefixList" => INC_PREFIX_LIST})
+      c14element = transforms_element.add_element("ds:Transform", {"Algorithm" => C14N})
+      c14element.add_element("ec:InclusiveNamespaces", {"xmlns:ec" => C14N, "PrefixList" => INC_PREFIX_LIST})
```

**Comment by pitbulk** [comment]
@bwillis Now the master branch has this issue solved.

Bug:
* InclusiveNamespaces was placed in the XML in a bad place.
* InclusiveNamespaces was not computed on the sign process.

**Comment by bwillis** [comment]
I was passively looking into this, but you beat me to it, thanks for fixing this!
