### ISSUE TITLE
0.9.2 release?

### ISSUE THREAD

**Issue by Umofomia** [onelogin/ruby-saml#217]
I know you guys are busy working on improving validations and supporting encryption, but is there a chance you could publish a new release for all the changes that have gone in since the 0.9.1 release? There have been several bug fixes and pull requests that have gone in so far that would be useful to have before the next major release:

#175 from phlipper/thread-safety
#199 from Umofomia/nokogiri-dependency
#200 from Umofomia/ruby-1.8-ssl-cert-store
#171 from GyldendalDigital/replace_unsafe_regex_response_handling
#204 from rafaelgonzalez/require-net-http
#201 from Umofomia/fix-default-security-settings
#179 from Pathgather/parse-entity-id
#205 from rafaelgonzalez/fix-single-file-requirements
#208 from onelogin/ruby-2.2.0
#210 from bwillis/add-asserts-in-test-cases
#212 from phlipper/rename-entrypoint
#214 from phlipper/cleanup-saml-message
#213 from onelogin/Umofomia-sign-metadata

**Comment by Lordnibbler** [comment]
@Umofomia I'm a bit slammed with work at the moment -- would you be willing to help by creating a branch for 0.9.2 and adding all merged PRs to the `changelog.md` file? I'll be happy to put out a release.

**Comment by Umofomia** [comment]
@Lordnibbler No problem; I just opened #219 for this. Thanks for taking it into consideration!

**Comment by Lordnibbler** [comment]
thanks @Umofomia I'll put this on my calendar to release 0.9.2 shortly

**Comment by Lordnibbler** [comment]
@Umofomia sorry for the delay: https://rubygems.org/gems/ruby-saml/versions/0.9.2

**Comment by Umofomia** [comment]
@Lordnibbler No problem... thanks for doing the release!
