### ISSUE TITLE
document.validate fails if ds:x509certificate is not embedded in the SAML Response

### ISSUE THREAD

**Issue by TJM** [onelogin/ruby-saml#220]
We are building an app that is going to do SSO with Ping Federate using ruby-saml, and I am told that the IdP is emitting valid SAMLv2 responses. However, the responses do not contain  the ds:x509certificate stanza. The certificate *is* available in the metadata.xml file, and it matches the signature in the SAML response. I am not sure why the cert would have to be embedded in the response, when it is already available in the metadata. We do have an option for "anchored" response that does include the certificate. So this is partially to help someone else in the future who runs into this same issue and partially to figure out why the certificate would be required in the SAML response. Our initial problem is solved, but it has left me wondering why. Hopefully someone can help.

~tommy

**Comment by TJM** [comment]
Quote from: http://stackoverflow.com/questions/1703301/saml-why-is-the-certificate-within-the-signature

> SAML responses do not require including the public key for that signature. Section 5.4.5 of the SAML2  spec states "XML Signature defines usage of the <ds:KeyInfo> element. SAML does not require the use of <ds:KeyInfo>, nor does it impose any restrictions on its use. Therefore, <ds:KeyInfo> MAY be absent." You can verify the signature if the public key has been provided to you through other means, e.g. stored in your local certificate store prior to implementing the SAML consumer. –  Sam.Rueby Nov 5 '14 at 16:01

**Comment by pitbulk** [comment]
The ruby-saml gem expects a Signed SAML Response, This Signature may carry a cert.
In our signature validation checking we extract the x509certificate from the SAMLResponse and compare it with the settings.idp_cert or the settings.idp_fingerprint.

Most of the Service Providers implementations works in this way.

The main reason is that most SAML implementations delegate on XMLSignature implementations that requires the KeyInfo element, but I'm agree that the spec says that SAML does not require it (. Section 5.4.5). 

Other reason for doing that is for avoiding DOS attacks (saml-sec-consider 5.2.1 Denial of Service).
Is fast/easy discard a SAMLResponse without cert or an invalid cert than verify the signature.

**Comment by TimMoore** [comment]
@pitbulk would you consider accepting a pull request that makes it optional in the response document if `settings.idp_cert` is defined?

**Comment by pitbulk** [comment]
@TimMoore, I posted why we implemented all our toolkits requiring the x509certificate data.

I think is easier configuring the Identity Provider side to inject the ds:x509certificate.
99% of Identity Provider implementations do that.

**Comment by TJM** [comment]
In our case, I was told that "it is a valid SAMLv2 response" by the IdP admins, which according to what I found above, is correct. They acted like including the certificate made it an "anchored" SAML assertion, which changed something about the validation. I basically just responded with a link to the code and a "text" description of the algorithm, which seemed to satisfy them. They "checked a checkbox" (?) and everything started working. It seems that, by default, they do not normally include the x509 cert in their assertions. Maybe they are a one off? Maybe not. I would say that, in order to be "compliant" with the standards as written, it should be coded to be optional. I don't think it would require significant code changes. Unfortunately, we are also off on #206 as well, due to jRuby requirements, so we are maybe not the best test case, but I would be willing to try if someone submitted it.

In any case, this issue should help someone else who encounters a similar issue, even if we don't change anything about the validation. :)

**Comment by pitbulk** [comment]
@TJM I appreciate it. Right now there are other priorities in the toolkit development process, but we will consider to add a settings to allow SAMLResponse without fingerprint, but this specific change means several changes on the code.

**Comment by patcheng** [comment]
One thing we noticed if you generate the metadata xml before you set the idp_cert in settings, the generated metadata claims that signed response is not required.

so, if the IDP admin generates the metadata xml first (before setting the idp_cert), the response won't be signed. But once they changed the configure to respond with signed request everything works.

instead of relaxing SAML response to accept unsigned request, maybe always generate the metadata to require signed response.

**Comment by pitbulk** [comment]
@patcheng, The toolkit reject any unsigned request.

**Comment by patcheng** [comment]
I think that's the issue.

When processing the response, the toolkit rejects anything that's unsigned. So the Metadata XML should always be WantAssertionsSigned="true"

But in https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb#L29

WantAssertionsSigned is set to true only when settings.idp_cert_fingerprint or settings.idp_cert is set. In our workflow at least, user will most likely generates the metadata before setting the idp certs.

**Comment by pitbulk** [comment]
@patcheng, We can have the WantAssertionsSigned=false and the IdP then add the Signature to the whole SAML Response message.

**Comment by jdleesmiller** [comment]
For the record, we've also hit this problem --- a customer's IdP is not including the certificate in each SAML response, only in their metadata.

First, I'd like to say thanks for providing this great library and the excellent documentation --- we definitely would not have gotten this far without it! However, we are a bit stuck without this option, since we don't have any control over what the IdP provides, and from the discussion above, it appears that they are already compliant with the standard.

**Comment by Bauerpauer** [comment]
Just ran into this as well.  If the vendor can't inject the cert into their response we'll have to resort to a one-off fork of this gem to get it working, which is unfortunate.  I echo @jdleesmiller here w/ the "Thanks, but we're a little stuck."

**Comment by jsom** [comment]
We're running in to the exact issue as @TJM as well. It should not be a required validation.

**Comment by pitbulk** [comment]
@Bauerpauer , @jdleesmiller , @TJM , @TimMoore 

Can you review this new branch that includes support on SAMLResponse that does not contain ds:x509certificate?

https://github.com/onelogin/ruby-saml/tree/no_x509certificate

**Comment by dtengeri** [comment]
Thanks @pitbulk , this worked for me.

**Comment by pitbulk** [comment]
@luisvm can you validate it before merge?

**Comment by TJM** [comment]
@pitbulk I am sorry, the project that I was working with on when we came across that requirement is no longer an active customer. Hopefully @jsom or someone can still reproduce it?

**Comment by davelooi** [comment]
Running into this problem. Any update on when this will be shipped?

**Comment by pitbulk** [comment]
Is merged.
