### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen - /nonexistent/.ruby-uuid):

### ISSUE THREAD

**Issue by kritiagg** [onelogin/ruby-saml#224]
I am trying to deploy a rails application using apache and passenger. I have also integrated it with Okta for authentication. Though everything seems to be working fine after bypassing the authentication or by using thin/webrick server. I am getting the following error in my error logs if I use apache:

    Errno::ENOENT (No such file or directory @ rb_sysopen - /nonexistent/.ruby-uuid):

It stops execution just after reaching saml init function while running " request = OneLogin::RubySaml::Authrequest.new". Does anyone has any idea what might be causing this?

**Comment by pitbulk** [comment]
First time I see this error, can you be more verbose on the trace error?

**Comment by kritiagg** [comment]
The issue was coming because the process did not have permissions on a folder. Its solved now.

**Comment by aarmora** [comment]
What process needed permission?
