### ISSUE TITLE
Clarification on signed authentication requests

### ISSUE THREAD

**Issue by ivanoblomov** [onelogin/ruby-saml#230]
A client library cites the lack of signed auth requests as a limitation (limitation #2 in https://github.com/apokalipto/devise_saml_authenticatable#limitations) and says this occurs in the ruby-saml layer...

https://github.com/apokalipto/devise_saml_authenticatable/issues/11#issuecomment-98765454

After thinking about it, can't we just install an SSL cert on the client app to make the SAML request securely? Or is the cited limitation a part of the SAML protocol itself?

Thanks in advance for any insight on this.

**Comment by pitbulk** [comment]
Notice that the ruby-saml toolkit is able to sign Authentication Request:
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb#L65

Read more info here:
https://github.com/onelogin/ruby-saml#signing
