### ISSUE TITLE
Recipient attribute not checked

### ISSUE THREAD

**Issue by theicfire** [onelogin/ruby-saml#233]
I'm fairly new to SAML, I'm curious why ruby-saml doesn't check any of:
- InResponseTo
- saml:AudienceRestriction
- recipient attribute

For the last one, 6.4.2 says "The Service Provider site MUST check the Recipient attribute of the SAML response": http://docs.oasis-open.org/security/saml/v2.0/saml-sec-consider-2.0-os.pdf)

**Comment by pitbulk** [comment]
We developed this functionality but is still under revision:
https://github.com/onelogin/ruby-saml/pull/197

(notice that this PR was so complex and I'm splitting it in minor PRs)

Soon all that and more will be covered.
