### ISSUE TITLE
When will 0.9.3 be released?

### ISSUE THREAD

**Issue by iyerk0** [onelogin/ruby-saml#242]
Can you indicate when you will release the the next version of ruby saml. I noticed that when i use the latest released version 0.9.2, i get errors on the samlcontroller#acs :+1: Getting OpenSSL::X509::CertificateError nested asn1 error on Ruby

However this error is not happening with the bleeding edge version of ruby-saml. As I integrate ruby saml into our project, it would be inadvisable for us to continue using the daily developer version.
I would request you to release the latest ruby saml , so it can be used in a stable manner.

Thanks!

**Comment by vincentwoo** [comment]
Seconding this motion! Would love to see a new gem cut whenever you have time!

**Comment by booleanbetrayal** [comment]
@pitbulk - can we get a 1.0.0 gem bump please? would like to get a dependency bump PR in for omniauth-saml, but would like to make it on the 1.0.0 version. Thanks!

**Comment by pitbulk** [comment]
@booleanbetrayal worning on that. I want to include that PR https://github.com/onelogin/ruby-saml/pull/247 and do the release.

**Comment by booleanbetrayal** [comment]
sweet! thanks!  =]

**Comment by pitbulk** [comment]
The 1.0.0 is drafted (same content that current master branch). 
We are reviewing it and soon it will be published on github and Rubygems.

We are also working on a new release of the [ruby-saml-example](https://github.com/onelogin/ruby-saml-example) compatible with this new version.

**Comment by iyerk0** [comment]
Thank you @pitbulk !

**Comment by pitbulk** [comment]
1.0.0 released and soon will be updated to rubygems.

Notice that we also released a new version of [ruby-saml-example](https://github.com/onelogin/ruby-saml-example/releases/tag/v2.0.2) that will use this gem.
