### ISSUE TITLE
Shibboleth won't accept signed metadata

### ISSUE THREAD

**Issue by soupmatt** [onelogin/ruby-saml#244]
Using both version v0.9.2 and current master (04659e543cf83228821496b5616e675b325d26b4), I cannot get a shibboleth IdP to validate my metadata.xml when I sign it. As I investigated this, it turns out the `KeyDescriptor` elements that are put inside the `SPSSODescriptor` aren't allowed by the xml schema. The ones inside the `Signature` element are fine.

Upon further investigation, it seems as if the metadata xsd included in ruby-saml has [two additional lines](https://github.com/onelogin/ruby-saml/blob/v0.9.2/lib/schemas/saml-schema-metadata-2.0.xsd#L250-251) in it that aren't present in the versions of the xsd that is packaged by [shibboleth](http://svn.shibboleth.net/view/java-opensaml/tags/3.1.1/opensaml-saml-api/src/main/resources/schema/saml-schema-metadata-2.0.xsd?view=markup#l229), [php-saml](https://github.com/onelogin/php-saml/blob/v2.5.0/lib/Saml2/schemas/saml-schema-metadata-2.0.xsd#L249) and [python-saml](https://github.com/onelogin/python-saml/blob/v2.1.3/src/onelogin/saml2/schemas/saml-schema-metadata-2.0.xsd#L249). The links lead to the relevant section of the xsd file in each projects' source tree. I used the latest release tags for each link.

Now, if there are installations that look for and benefit from these KeyDescriptors being included, then perhaps a config switch to take them would be in order. Otherwise, I propose they be removed. I am happy to contribute a pull request to either end.

**Comment by iyerk0** [comment]
I verify this issue exists. I have also had a tough time importing a valid sp metadata xml into various IDPs. Current hack is that I manually edit the exported xml from ruby-saml and re-order the elements to get the validation to pass in the IDP.
It is definitely a nasty blocker for people new to ruby saml
Request a fix for this
