### ISSUE TITLE
response.errors empty after validation fails

### ISSUE THREAD

**Issue by bjm88** [onelogin/ruby-saml#248]
If I just run  response.is_valid?
when false try to log for debugging
response.errors
its empty.  If I do response.validate!
that throws exception where I can then get actual useful error messages.  I feel like .errors should be populated either way....perhaps fixed in master just not 0.9.2, not sure?

**Comment by bjm88** [comment]
FYI I'm talking about consume method on service provider side.

**Comment by pitbulk** [comment]
The new 1.0.0 contains [changes](https://github.com/onelogin/ruby-saml/commit/e10328afaa845f97e620acd4394d805d7d4d0968) related to this issue.

In this new version you can handle if the errors gonna raise or not an exception by the settings.soft parameter. We added more validations and all errors are stored on errors.

At 0.9.2 version
validate! executes a validate method with soft=false (will raise exception)
is_valid? executes a validate method with soft=true so errors on validation will not raise exceptions.

**Comment by pitbulk** [comment]
@bjm88 have you tested the new release?
