### ISSUE TITLE
Push 1.0.0 to rubygems.org ?

### ISSUE THREAD

**Issue by jbandhauer** [onelogin/ruby-saml#250]
This is an awesome gem. 1.0.0 looks like a great update. Is there a reason to not push the new version to rubygems.org yet? Thanks!

**Comment by vincentwoo** [comment]
Also eagerly awaiting the ability to remove my gemfile's github dependency :)

**Comment by Lordnibbler** [comment]
Done! https://rubygems.org/gems/ruby-saml/versions/1.0.0

**Comment by jbandhauer** [comment]
Thanks!

**Comment by vincentwoo** [comment]
beautiful
