### ISSUE TITLE
Create security disclosure / handling policy

### ISSUE THREAD

**Issue by reedloden** [onelogin/ruby-saml#252]
With several security issues in `ruby-saml` being fixed so far this year, it would be a good idea to have a vulnerability reporting process to ensure things are handled correctly, CVEs requested, notifications to appropriate forums / lists / databases made (oss-security, OSVDB, rubysec), etc.

Here's some recent other discussions from other projects on this same topic:
* https://internals.rust-lang.org/t/proposed-security-disclosure-policy/2024
* https://github.com/sparklemotion/nokogiri/issues/1191

The Ruby on Rails team uses HackerOne for this purpose (https://hackerone.com/rails, as mentioned on http://rubyonrails.org/security/), and it seems to really work well for them, so that's one option (disclaimer, I lead security for HackerOne, though I truly think our platform is amazeballs).

Main thing is just to have a defined process that works for everybody and is followed. Whether that's just some private e-mail address or use of some platform or whatever in the end.

Happy to help in any way I can... Security is my full-time job, so used to dealing with this stuff.

**Comment by reedloden** [comment]
Any thoughts, @pitbulk?

**Comment by pitbulk** [comment]
Hi @reedloden , I'm not the one that must decide this. I will reference this to the OneLogin's Chief Information Security Officer.

**Comment by reedloden** [comment]
Bump on this, given the recent security issue fixed in v1.3.0. Would be good to have some type of policy/process around this and a defined path for people to report issues related to this gem. Perhaps that's just pointing to https://www.onelogin.com/security and explaining what the expectations are around vuln handling? Just unclear currently.

**Comment by pitbulk** [comment]
Yes, https://www.onelogin.com/security should be the place to report them

**Comment by pitbulk** [comment]
Added reference to Security Guidelines 
https://github.com/onelogin/ruby-saml/commit/47b7a8efec960b49a9d56391687f88b4e219b7c2

**Comment by reedloden** [comment]
Awesome, thanks so much!
