### ISSUE TITLE
ruby-saml/testing environment variable

### ISSUE THREAD

**Issue by mfoo** [onelogin/ruby-saml#257]
Hi all,

May I ask what this is?

https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/logging.rb#L18

"Don't log anything if this environment variable is set and isn't false".

Why does it control both debug and info level logging, and why is it undocumented? I see no reference to this environment variable anywhere else in this project.

If it's to prevent logging to stdout on some build server then surely there's a better way.

Edit: This is pretty funny actually. The only info level log this project makes is from the tests, logging a 'sup?' string from a test, yet this function exists to disable the output (probably during tests) :)

**Comment by pitbulk** [comment]
@mfoo do you have a PR/suggestion for improve the logging process?

**Comment by johnnyshields** [comment]
This code is fine as-is. Let's close this issue.

**Comment by mfoo** [comment]
Yep, looks like the variable isn't used any more so it's not an issue. Thanks for taking a look and closing this issue. Also I'd like to apologise for my 6-year-ago-self's "this is pretty funny actually" - just in case it sounded rude!
