### ISSUE TITLE
ruby-saml library invalidating SAML assertion signature where xmlns:ds namespace declaration is missing

### ISSUE THREAD

**Issue by dgindin-cp** [onelogin/ruby-saml#264]
We are using your ruby-saml library to enable SSO for customers into our web application.

One of our customers is using Tivoli's FIM platform for SAML SSO. Previously they only signed their SAML assertion and everything worked fine. The OneLogin ruby-saml library began invalidating their SAML assertion signature when they began signing their SAML assertion and response. After some troubleshooting we discovered that the Tivoli FIM platform moved the `xmlns:ds="http://www.w3.org/2000/09/xmldsig#"` namespace declaration out of the assertion signature element and put it in the first line of the `<samlp:Response>` element expecting it to be inherited by any `<ds:signature>` elements that follow. This behavior appears to be hard-coded into the Tivoli FIM product and may be impossible to change.

Is there any way to get the OneLogin ruby-saml library to honor the `xmlns:ds="http://www.w3.org/2000/09/xmldsig#"` namespace when it is declared only once at the top of the SAML response?

Thanks!

Here is a copy of the SAML response (relevant elements only) that ruby-saml sees as invalid:

```lang-none
<samlp:Response xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
....
<saml:Assertion ID="Assertion-uuidae349e99-014f-11c6-844c-a6a86d8ccbb1"
IssueInstant="2015-09-08T18:25:28Z"
Version="2.0">
<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://abc.com/auth/sps/samlidp/saml20</saml:Issuer>
<ds:Signature Id="uuidae349e9a-014f-1e8d-b0b2-a6a86d8ccbb1">
....
```

**Comment by pitbulk** [comment]
SAML implementations used to delegate Signature/Encryption on 3rd party libraries.
The problem is that in order to decrypt or validate a sign the 3rd party library expects the part that you want to valdate/decrypt , not the whole XML. Not providing the namespace on the part will produce decrypt/sign validation problems.

That is why most of the SAMLResponse that you will see not declares ds/xs/xsi on the top.

A possible trick to solve it: Before decrypt/validate the signed element, check if contains the namespace and if they are not there, inject them (but only a duped version, never modify the original).

**Comment by dgindin-cp** [comment]
Sixto,

Any plans for OneLogin to update its ruby-saml library to inherit and honor namespaces declared at the top of an SAML XML document?

**Comment by pitbulk** [comment]
Right now I'm focused on the java-saml improvement. (It will take 2-3 weeks more). After that we will improve these kind of issues.

**Comment by pitbulk** [comment]
@dgindin-cp this should solve your issue:
https://github.com/onelogin/ruby-saml/commit/46c221f6bc3379523781394e4a34b7329d5a4e18

**Comment by phene** [comment]
I'm also running into this issue, in combination with `xmlns:ds` becoming `xmlns:dsig`

**Comment by Vsandhya11** [comment]
I am also facing this issue, When SAML response comes back to SP got the following error.
SAML Response invalid
Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd

Thanks in advance!
