### ISSUE TITLE
Or operation in identifier

### ISSUE THREAD

**Issue by Karamorf** [onelogin/ruby-saml#265]
At my organization, there is no single one piece of identifier that might not change over the course of a persons career. Ideally, the identifier format could support an "or" type operation so that any identifying piece of information from the saml response could map to the same account in the system.

Ideally, this setting:
settings.name_identifier_format         = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

Could be defined like this:
settings.name_identifier_format         = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress|guid|uid|..."

**Comment by pitbulk** [comment]
In most of the cases, the Identity Provider provides not only a NameID, instead a set of attributes of the user. The attribute mapping can be coded at the ServiceProvider side, the ruby gem will parse the NameID and the attributes and based on a mapping, will try to identify the user in the local application.
