### ISSUE TITLE
Support Multiple Signing Certificate - Handling Expiration

### ISSUE THREAD

**Issue by gmontard** [onelogin/ruby-saml#266]
Hello,

We are implementing signing on our SP, but it seems we can only have one certificate which lead me to the question of how to handle the expiration?

What people seems to do is to implement the option to have two certificates, so a little bit before the cert expire you can generate a new one and have in the mean time the new and the old on the Manifest which give enough time for the IDP to do the switch because for some time both are valid.

Is there anyway to do that using Ruby SAML Gem?

Thanks,

Guillaume.

**Comment by pitbulk** [comment]
Key/Certificate rollover is not officially supported on the ruby-saml gem and is not trivial to add that functionality.

**Comment by gmontard** [comment]
I understand.

Would you have any recommandation to share on how to manage those certificate rollover?

Thanks.

**Comment by yoda** [comment]
I would also like to know about this. Thanks for all the effort on this gem.

**Comment by rjnordeen** [comment]
Also interested in this as well - anyone else found a way of doing this with ruby-saml?

**Comment by gmontard** [comment]
Isn't it the goal of this PR? #290 by @davelooi?

**Comment by pitbulk** [comment]
We don't plan to support multiple certificates, but if you are in a Key/Certificate rollover, you can 
dynamically change the value of the cert.

An ACS example endpoint:
```
def consume
    response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], :settings => settings)
    # We try to validate the SAML Response with one certificate
    valid = false
    if response.is_valid?
        valid = true 
    else
        # We try to validate the SAML Response with the other certificate
        settings.idp_cert = "<-----alternative cert----->"
        response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], :settings => settings)
        if response.is_valid?
            valid = true 
        end
    end

    if valid
       # authorize_success, log the user
       session[:userid] = response.nameid
       session[:attributes] = response.attributes
     else
         authorize_failure  # This method shows an error message
    end
  end
```

**Comment by gabriel-kaam** [comment]
If somebody stumble accorss this thead, have a look at https://github.com/onelogin/ruby-saml/pull/389 and you'll be happy :)
