### ISSUE TITLE
IdP initiated sessions

### ISSUE THREAD

**Issue by netpenthe** [onelogin/ruby-saml#272]
In the main documentation of this (https://github.com/onelogin/ruby-saml), in particular the *The Initialization Phase* part of the documentation, it says the flow will include redirects to the IdP to verify the user is authorized.

Am I right to presume this is ONLY for SP-initiated flows?

For IdP initiated sessions, there would be NO redirect - the SP would only ever receive the one HTTP request containing the user information (in SAML format) and a fingerprint that you use to authenticate it?

**Comment by pitbulk** [comment]
@netpenthe You are right,

In SP-initiated SSO flow:
1. SP sends an AuthNRequest to the IdP (HTTP-Redirect binding)
2. IdP replies a SAMLResponse (HTTP-Post binding) 

In IdP-initiated SSO flow:
1. IdP sends a SAMLResponse (HTTP-Post binding)
