### ISSUE TITLE
Upload 1.1.0 release to Rubygems

### ISSUE THREAD

**Issue by alex** [onelogin/ruby-saml#274]
Thanks for cutting a release! I see that it's been tagged on github, but doesn't appear to be on rubygems yet -- https://rubygems.org/gems/ruby-saml still shows 1.0, it'd be great to upload it so we can depend on it in our `Gemfile`.

**Comment by pitbulk** [comment]
Done.

Please, notify me if you experience any error with the new gem:
https://rubygems.org/gems/ruby-saml/versions/1.1.0

**Comment by alex** [comment]
Thanks! (We started running from the tag as soon as it was released, since we needed #271, looks good!)
