### ISSUE TITLE
Problem validating document with multiple Signature elements

### ISSUE THREAD

**Issue by levelboy** [onelogin/ruby-saml#275]
The lastest release of the gem (1.1.0), fails to validate documents of this form:

````
<samlp:Response>
	<saml:Issuer></saml:Issuer>
	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
			<ds:Reference URI="#_f7379ea04746ee86b0a16f519aea47c83cd0eefad0">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
				<ds:DigestValue></ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue></ds:SignatureValue>
		<ds:KeyInfo>
			<ds:X509Data>
				<ds:X509Certificate></ds:X509Certificate>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<samlp:Status>
		<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
	</samlp:Status>
	<saml:Assertion ID="_a945e7e0e04ae098e9603cdcd9360f4a3d558198b1" IssueInstant="2014-12-08T16:22:43Z" Version="2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
		<saml:Issuer></saml:Issuer>
		<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
				<ds:Reference URI="#_a945e7e0e04ae098e9603cdcd9360f4a3d558198b1">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
					<ds:DigestValue></ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
			<ds:SignatureValue></ds:SignatureValue>
			<ds:KeyInfo>
				<ds:X509Data>
					<ds:X509Certificate></ds:X509Certificate>
				</ds:X509Data>
			</ds:KeyInfo>
		</ds:Signature>
		<saml:Subject>
			<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"></saml:NameID>
			<saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<saml:SubjectConfirmationData InResponseTo="_79f6013431c8237f4de1c57ee7c9f11b8b3c701894" NotOnOrAfter="" Recipient=""/>
			</saml:SubjectConfirmation>
		</saml:Subject>
	</saml:Assertion>
</samlp:Response>
````

I tracked the problem in the xml_security.rb https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L234

Within each signature element, we try to get the Reference node and match the digest_value with the computed hash of the referenced node.
When we get the ````encoded_digest_value```` from the Signature element, we use this: https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L307, note the ````//ds:DigestValue````. This scopes the call to the whole document and always returns the first DigestValue in the document, regardless of the context element we passed to the call so it always compares the first digest value in the document with the computed hashes of each of the Referenced nodes hence the validation fails. See this answer on SO: http://stackoverflow.com/a/32640500

1. Is this intended behavior or is it a bug? I can write a PR to fix this.
2. Why are two XML parsing libraries used? I see both nokogiri and rexml being used here
3. Have you considered using an external library for the signature verification? (e.g. https://github.com/sinisterchipmunk/xmlsec#nokogiri-xmlsec)

Thanks

**Comment by phene** [comment]
+1 for addressing this -- My team also ran into this issue.

**Comment by pitbulk** [comment]
Maybe this was introduced at this change:
https://github.com/onelogin/ruby-saml/commit/275512af57a8395efdde76dece8c94e2aa4662e2

1. Please provide a PR and test so others that experience same issue can review.
2. We plan to refactor all the signature/encrypt methods in a new gem and avoid using 2 XML parsing libraries.
3. It seems that there is no external library that offer what we required. 
The library that you mentioned, for example, is not completed (has limitations)

**Comment by levelboy** [comment]
@pitbulk Added a PR for this. It has the least amount of change to validate documents, and the modification is according to the fact that a Signature element can only have one Reference node inside.
What's your timeframe for the xml_security refactoring. I would highly like to contribute to that.

**Comment by levelboy** [comment]
btw, if it's not a big hassle, I would greatly appreciate if you can release a new version of the gem (say 1.1.1). I've been waiting for a long time for this. Thank you

**Comment by aaronchi** [comment]
I have this problem as well after 1.1

**Comment by pitbulk** [comment]
@phene I released 1.1.1 version. Please try it and let me know if the problem is gone.
@levelboy thanks for the PR, I will release it at Rubygems as soon as we get more feedback on that issue.

**Comment by phene** [comment]
I'm now getting the following error validating the response:

```
#<OneLogin::RubySaml::ValidationError: Element '{http://www.w3.org/2000/09/xmldsig#}X509Certificate': 'MIICmTCCAgKgAwIBAgIGAUPARxYtMA0GCSqGSIb3DQEBBQUAMIGPMQswCQYDVQQGEwJVUzETMBEG\nA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEU\nMBIGA1UECwwLU1NPUHJvdmlkZXIxEDAOBgNVBAMMB3Bpdm90YWwxHDAaBgkqhkiG9w0BCQEWDWlu\nZm9Ab2t0YS5jb20wHhcNMTQwMTIzMTgwNDIwWhcNNDQwMTIzMTgwNTIwWjCBjzELMAkGA1UEBhMC\nVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDTALBgNVBAoM\nBE9rdGExFDASBgNVBAsMC1NTT1Byb3ZpZGVyMRAwDgYDVQQDDAdwaXZvdGFsMRwwGgYJKoZIhvcN\nAQkBFg1pbmZvQG9rdGEuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCuyLk84lq6sonC\nBAYuGvL/bYeYNpfaBPXvINwao/m8N/PDTKEeu5+2ThC5mBPLGkvFbcbzSE/rpOtvlRh9e6CsrtqK\noZBGRF/a4ogMj0mZ7JrP2N4928xDKPaZibX/Q3Q4ZWj7mXxF7eZdmffhZyM0+61TMEQJP8O72Ykj\n/YXD1wIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAEVhizwN9yJqHfKzoJySjTUMY5z0u6N1yOYTVdoi\nTrc8cKV/6cmbHpFihVwZzwilw5dbCmSnbw65RTIxBIbkvDZgkzQ78sbBKA3oFcViq9ebCUjL5iq6\nnpTU8uwpoMB18ex9yfSUj0zIWwqQNr4ml4vGbHkhO2A7GyVzakxml0xL
       ' is not a valid value of the atomic type 'xs:base64Binary'.
```

**Comment by akash-goel** [comment]
I try to add SSO (single sign-on) and use SAML2 protocol. 

It works well when we run the application, but when we run the test cases then it gives the digest mismatch and signature validation error.

We have checked the Configuration and configuration is same in both the cases.

Request to share the parameters which are responsible for changing Signature Validation and digest mismatch error
