### ISSUE TITLE
sso_target_url is arbitrary when parsed from idp metadata file

### ISSUE THREAD

**Issue by kahlouie** [onelogin/ruby-saml#279]
There are two similar binding fields in an IdP metadata file: `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST` and `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`. The `single_signon_service_url` that creates the sso_target_url [arbitrarily chooses the first of these two binding fields](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L116-L123). There should be an option to choose the one needed. Many IdPs appear to use the same value for the `HTTP-POST` and `HTTP-Redirect`; however, when they don't, some single sign on implementations will break.

**Comment by joshwlewis** [comment]
Hi -- I'm interested in helping fix this if possible. We're using your `IdpMetadataParser`, but we can't be sure whether we get a Redirect or a Post endpoint from `single_signon_service_url`.

Based on [this comment](https://github.com/onelogin/ruby-saml/blob/2ee7b3902e67e3ef69cc8ec415a7d3f3f14716ac/lib/onelogin/ruby-saml/settings.rb#L96), it looks like `RubySaml` is only supporting `HTTP-Redirect` for the `single_logout_service_url`. Can we make the same restriction for the `single_signon_service_url`?

**Comment by pitbulk** [comment]
Both SSO and SLO should be HTTP-Redirect, can you provide a PR?

**Comment by joshwlewis** [comment]
Yep, we sure will. @kahlouie is working on it now. Thanks!

**Comment by pitbulk** [comment]
Fixed
