### ISSUE TITLE
Schema loading fails with jruby and warbler

### ISSUE THREAD

**Issue by tomilaine** [onelogin/ruby-saml#293]
I have a problem with using ruby-saml with jruby and warbler. Since warbler packages the gems inside a jar changing the directory won't work (https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/saml_message.rb#L27). 

```
[2015-11-20 14:22:33.178] FATAL  Errno::ENOENT (No such file or directory - /opt/apps/foo/releases/20151118111323/WEB-INF/lib/gems.jar!/gems/ruby-saml-1.0.0/lib/schemas):
  lib/gems.jar!/gems/ruby-saml-1.0.0/lib/onelogin/ruby-saml/saml_message.rb:27:in `schema'
  lib/gems.jar!/gems/ruby-saml-1.0.0/lib/onelogin/ruby-saml/saml_message.rb:26:in `schema'
  lib/gems.jar!/gems/ruby-saml-1.0.0/lib/onelogin/ruby-saml/saml_message.rb:75:in `valid_saml?'
  ...
```

(reason for 1.0.0 is that I'm using ruby-saml through omniauth-saml, not that it should make a difference here?)

The files are accessible with their full paths though, so I tried to solve the problem by giving Nokogiri a file handle instead, which gets rid of the chdir (https://github.com/tomilaine/ruby-saml/commit/cc3bffccb1116e78276ecc2a2d80b121de5c3d3b). That passes ruby-saml tests fine. Still with jruby & warbler environment it fails. It loads the top xsd fine but then fails in actual validation by giving bogus errors meaning it apparently doesn't read in properly the other relative xsds.

I resorted in copying the schema files to the file system and monkey patching the path. After that everything works but it's not a nice solution. Any better ideas?

**Comment by jv-dan** [comment]
This is definitely not just limited to this scenario. When using a build job that runs: 
`bundle package --all`, changing directory also doesn't work.

**Comment by pitbulk** [comment]
@jv-dan do you have a patch?

**Comment by jv-dan** [comment]
@pitbulk : My comment is actually incorrect. I updated it to reflect this. Working like a dream with packaged gems.
