### ISSUE TITLE
update toolkit URL in description of github repo

### ISSUE THREAD

**Issue by KevinColemanInc** [onelogin/ruby-saml#294]
Should be this:
https://developers.onelogin.com/v1.0/page/saml-toolkit-for-ruby-on-rails

not this:
http://support.onelogin.com/entries/165434-saml-toolkit-for-ruby-on-rails

**Comment by pitbulk** [comment]
Where is that link?

**Comment by KevinColemanInc** [comment]
<img width="1146" alt="screen shot 2015-12-08 at 3 48 14 pm" src="https://cloud.githubusercontent.com/assets/2381771/11672182/22acae94-9dc3-11e5-8bb3-e2a3e416be4c.png">

**Comment by pitbulk** [comment]
Ok, let me find someone with privileges to change that

**Comment by tinifni** [comment]
@KevinColemanInc updated. Thanks :+1:
