### ISSUE TITLE
Copy/paste error?

### ISSUE THREAD

**Issue by wbajzek** [onelogin/ruby-saml#295]
Is this the correct explanation of the query_string parameter? It would be nice to have a clearer explanation either way. 
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/utils.rb#L68

Thanks!

**Comment by pitbulk** [comment]
Fixed. https://github.com/onelogin/ruby-saml/commit/45665bac6f33f656273517e7107122dbe81cd252
