### ISSUE TITLE
gem installation error: mini_portile2 requires Ruby version >= 1.9.2

### ISSUE THREAD

**Issue by andrxu** [onelogin/ruby-saml#300]
Hi:
I got above error when installing the gem, does the gem still support the old ruby 1.87? 

Thanks

Andrew

**Comment by pitbulk** [comment]
Yes, if you using ruby 1.8.7 you can install mini_portile 0.6.2

**Comment by vipulvkp** [comment]
Hello, I tried the above solution. But still it shows the same message.

**Comment by pitbulk** [comment]
Sadly [mini_portile2](https://rubygems.org/gems/mini_portile2) removed the version that were compatible with ruby 1.8.7 from rubygems., version v0.7.0 removed the compatibility, that why you may install 0.6.2 version.

The gem mini_portile2 is a dependency of recent versions of nokogiri. 

Try to install first nokogiri 1.5.10

**Comment by santhoshcd** [comment]
Hi
       I already installed nokogiri (1.5.10) and mini_portile (0.6.2) gem in my app(ruby 1.8.7, rails 2.3.2) still, I am getting the same error.
**ERROR: Error installing ruby-saml:**
**mini_portile2 requires Ruby version >= 1.9.2.).**

Question
Are there any other dependencies?
How to solve this issue?

I asked question in [349](https://github.com/onelogin/ruby-saml/issues/349)


Thanks

**Comment by pitbulk** [comment]
It seems that ruby-saml is not currently working on 1.8.7 due mini_portile.
https://github.com/flavorjones/mini_portile/issues/45

I will try to investigate.

**Comment by pitbulk** [comment]
In Travis CI we are able to pass the [1.8.7 test](https://travis-ci.org/onelogin/ruby-saml/jobs/149829147)
maybe you can review how is done.

**Comment by santhoshcd** [comment]
Hi Pitbulk
               I am able to install ruby-saml in my application (ruby 1.8.7) and able to use ruby-saml (SSO and SLO function) but I am getting below error.
Fetching: ruby-saml-1.3.0.gem (100%)
ERROR: Error installing ruby-saml:
mini_portile2 requires Ruby version >= 1.9.2.

gem li 
**** LOCAL GEMS ****
**ruby-saml (1.3.0)**
**mini_portile (0.6.2)**

My doubt is, 
is there any other problem because of this error?

Why I am asking this question because we have a plan to install ruby-saml (1.3.0) gem in production (enterprise application). We don't want to get any other problem in production because of this error.

Please help

**Comment by santhoshcd** [comment]
Any update on this issue?

**Comment by richaasinha** [comment]
Hi,

I am also facing the same issue. So I have an application running on 

> ruby 1.8.7

 with 

> rails 2.3.2
> mini_portile 0.6.2
> ruby-saml 1.3.0
> nokogiri 1.5.10

Although I am getting an error while installing ruby-saml(ERROR: Error installing ruby-saml, mini_portile2 requires Ruby version >= 1.9.2).

How do I install it properly without any error.

**Comment by santhoshcd** [comment]
Any update on this?

**Comment by pitbulk** [comment]
Can you try this?

Let's suppose you have ruby 1.8.7, at the ruby-saml folder, try:
```
rvm use 1.8.7 --install --binary --fuzzy
export BUNDLE_GEMFILE=$PWD/gemfiles/nokogiri-1.5.gemfile
bundle install
```

**Comment by santhoshcd** [comment]
thanks @pitbulk , i will check this solution.

**Comment by pitbulk** [comment]
@santhoshcd any luck?

**Comment by n3rve** [comment]
You can force install the module:
`gem install ruby-saml -v 1.1.1 --ignore-dependencies`

**Comment by johnnyshields** [comment]
This issue should be closed. Ruby 1.8.7 is deep, deep EOL and it looks like there's a workaround on this thread.

**Comment by pitbulk** [comment]
I left it open in case someone experienced the same issue.

**Comment by johnnyshields** [comment]
OK, please close when you accept the Ruby < 2.1 removal PR "soon" :)

**Comment by Jmfwolf** [comment]
This issue has been resolved, I am closing it.
