### ISSUE TITLE
KeyInfo support in metadata

### ISSUE THREAD

**Issue by meenxo** [onelogin/ruby-saml#305]
I was asked by an IdP to insert our certificate name in KeyDescriptor -> KeyInfo -> KeyName. I don't see where the KeyDescriptor could be set and I can't find much information doing a google search. Is that something that will be supported in the future? Or is there a reason why it cannot be supported that I am not getting? I appreciate any feedback. Thanks

**Comment by pitbulk** [comment]
KeyDescriptor -> KeyInfo -> KeyName is not supported instead you can use KeyDescriptor -> KeyInfo -> [X509Data](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb#L42).

**Comment by meenxo** [comment]
Thanks for confirming.
