### ISSUE TITLE
invalid SAMLRequest generation

### ISSUE THREAD

**Issue by chetanbissa27** [onelogin/ruby-saml#309]
Hi

In setting I am using certificate and private key.
`settings.private_key = <<EOS`
`-----BEGIN PRIVATE KEY-----`
`###my key here####`
`-----END PRIVATE KEY-----`
`EOS`
`settings.certificate = <<EOS`
`-----BEGIN CERTIFICATE-----`
`####my certificate here#####`
`-----END CERTIFICATE-----`
`EOS`

`settings.security[:authn_requests_signed]   = true`
`settings.security[:logout_requests_signed]  = true`
`settings.security[:logout_responses_signed] = true`
`settings.security[:metadata_signed]         = true`
`settings.security[:digest_method]    = XMLSecurity::Document::SHA1`
`settings.security[:signature_method] = XMLSecurity::Document::RSA_SHA1`
`settings.security[:embed_sign] = false`

but when I my request is redirecting to adfs server which lands to error page.when I  decode SAMLRequest from [https://idp.ssocircle.com/sso/toolbox/samlDecode.jsp](url) it show `Not able to decode`

Please let me know where I am wrong.

**Comment by pitbulk** [comment]
Can you try this tool instead? https://www.samltool.com/decode.php
Also without the SAMLRequest, I can figure out what is happening. settings apparently seems ok.

**Comment by chetanbissa27** [comment]
below is my saml request

`fVLLbtswEPwV3XiSuJIQOyEsA4aNAgLSB%2Bymh14Kllw3BCRS5a5S9e9LqXHrS3zlPHY4uxvSfTeo3cjP%2Fog%2FRyTOdkQY2QW%2FD57GHuMJ44sz%2BHR8bMQz80BKyhKKCor7orx7UDUAyDGJSM52Uic3kR2Sl%2FN6Nvov0%2FZMnIBEfsFYTCE67bkwoV8g2ZFs7dB6x04z2pP74T%2F6QtMwiaw9NOLb2mi7Rg25sSubQ1nXOYD9nsM9QLVG%2B2DgLlGJRmw9cTJvRAXlKoc6L1efYaWqWpX1V5F9SXmXbFUBIpv6zpOa4zdijF4FTY6U1z2SYqNOu%2FePKhGVvpRzLRlua4YYOJjQie1mZqslXdy%2BWeVGXtM2f1f0Idm2h0%2Bhc%2BZ3tuu68GsfMXXUCI4jiuxdiL3m20HmF2fz80JVHLUnh56FvAx5PQG0y0Gk%2FTNOnO1DP%2BjoaC4LJ2348pFr1r5L1RzxvH1NfwN7Y84%2F9Poat38A&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=Bd06Y0EaQAOk7hvGJc8uDOKbSMNeQR3Mf76tUQAnJWby3Bz%2BjCz%2FQbGJKs2e%2BDLNo%2Foc%2F4sK5vCNTu%2B9lEBD2U43oTPmO1M9DkHfFzm%2BjilI4DTLVCzv2jK1WUAsB7tBVOdErMr8PptHFv0WqDYqnSDSoppR27LFA3bAMRwWVyALnvb3%2BSReMatYt%2Fhl7zRnOppc63J3zsvkz4BnUOVlP666Wq2UskljQJA4uj9LVH2%2FyeuZofV%2Fg7ziVs5aKOpkMkHTFIncS4eq4YEeEoXuvyiZ8J3bJDSRKF6Zzap405ihrVFywCkRaMKfE2y2BoZ1R1jDmzMgkzXciJQccJJwnQ%3D%3D`

**Comment by pitbulk** [comment]
I was able to decode the AuthNRequest:
```
<?xml version="1.0"?>
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://10.20.8.159:3000/users/saml/auth" Destination="https://adfstestserver.xoriant.com/adfs/ls/IdpInitiatedSignOn.aspx" ID="_7cad7ea0-cd6d-0133-00db-080027ed9c05" IssueInstant="2016-03-16T06:23:13Z" Version="2.0">
  <saml:Issuer>https://10.20.8.159:3000/</saml:Issuer>
  <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
  <samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef/>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

The data that you provided was urlencoded, so you need to first [urldecode](https://www.samltool.com/url.php) and then [Base64 Decode + Inflate](https://www.samltool.com/decode.php)

The samlDecode.jsp from ssocircle does not expect the AuthNRequest deflated, that why fail.
