### ISSUE TITLE
ruby-saml broken with default behavior of onelogin test connector

### ISSUE THREAD

**Issue by vincentwoo** [onelogin/ruby-saml#310]
If you make a onelogin SAML test app, and leave the optional "Recipient" field blank, enelogin sends a response like this:

```xml
<samlp:Response xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
ID="R4322a57992ebc681fe04a7ebeba94b6a9b010c8f"
Version="2.0" IssueInstant="2016-03-16T23:18:05Z"
Destination="{recipient}" InResponseTo="_3b4260d0-cdfb-0133-5f7d-6476bab6320c">
```

The `Destination="{recipient}"` bit breaks `ruby-saml`'s destination validation:

`The response was received at {recipient} instead of http://localhost:8080/saml/acs`

**Comment by pitbulk** [comment]
Don't leave it blank, instead set the Service Provider Assertion Consumer Service URL.

**Comment by vincentwoo** [comment]
That's crazy. It's an optional field - leaving it blank should not cause *your* gem to break with *your* test integration.

**Comment by pitbulk** [comment]
@vincentwoo  can you report that issue on Onelogin platform? Here we open issues related to the ruby-saml toolkit

**Comment by vincentwoo** [comment]
I don't know how to do that and would prefer that you did it for me - this issue is also a useful signpost for anyone using the library who hits the same problem.

**Comment by pitbulk** [comment]
I already reported that to the "platform team", I asked you to create the ticket to allow you follow the progress. 

But it is ok, Thanks for contribute.

**Comment by nerdyworm** [comment]
I also ran into this issue.

The correct walk around is setting the Recipient field in the Onelogin's SAML configuration page.
