### ISSUE TITLE
parse remote got http exception: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by andrxu** [onelogin/ruby-saml#311]
idp_metadata_parser.parse_remote("https://example.com/auth/saml2/idp/metadata")

I have no problem to access the meta data xml from browser and curl command, but not from my ruby 1.87, any idea to get it work? 

Thanks

andrew

**Comment by pitbulk** [comment]
maybe some ruby internal restriction with the example.com domain?

**Comment by andrxu** [comment]
No, I was trying to access https://fs.usd259.net/FederationMetadata/2007-06/FederationMetadata.xml, I guess it must be related to ruby or some ssl cert issue.  Thanks.
