### ISSUE TITLE
decrypting encrypted assertions in ruby-saml is broken

### ISSUE THREAD

**Issue by vincentwoo** [onelogin/ruby-saml#312]
for responses that look like:

```xml
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
    <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_c49ba4078e1f4e7c890eec5c488cf4d5" Type="http://www.w3.org/2001/04/xmlenc#Element">
      <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_b8fba8d1aab229c5b42f0fb1a78e239d"/>
      </ds:KeyInfo>
...
```

Ruby saml tries (https://github.com/onelogin/ruby-saml/blob/45665bac6f33f656273517e7107122dbe81cd252/lib/onelogin/ruby-saml/utils.rb#L127) to access an XPath inside `ds:KeyInfo` that doesn't exist, which explodes. Note that decrypting this response online with the tools you make at samltool.com work perfectly well.

**Comment by vincentwoo** [comment]
Actually, this may be due to this response having

```xml
<xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_b8fba8d1aab229c5b42f0fb1a78e239d">
  <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5"/>
  <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
    <xenc:CipherValue>...</xenc:CipherValue>
  </xenc:CipherData>
  <xenc:ReferenceList>
    <xenc:DataReference URI="#_c49ba4078e1f4e7c890eec5c488cf4d5"/>
  </xenc:ReferenceList>
</xenc:EncryptedKey>
```

Living outside of `ds:KeyInfo`. In this response, it appears to be the last child of `<saml2:EncryptedAssertion>`

**Comment by vincentwoo** [comment]
In the first random SO question I just found: http://crypto.stackexchange.com/questions/24448/decrypt-a-saml-2-0-response-having-aes-128-and-rsa, the sample XML there as well appears to have `xenc:EncryptedKey` not under `ds:KeyInfo`.

Ruby-saml tries to do: `  "//xenc:EncryptedData/ds:KeyInfo/xenc:EncryptedKey/xenc:CipherData/xenc:CipherValue",`

**Comment by vincentwoo** [comment]
Okay, I made a PR that makes `ruby-saml` able to process the responses I am getting. I don't know if this key element can belong in multiple locations or what, so I look forward to any information that anyone can provide, here.

It's also perhaps relevant that these responses I am receiving aren't from some random rogue IDP operator - they come from a very large company I'm not allowed to name. You probably own one of their products.

**Comment by vincentwoo** [comment]
@pitbulk this should be fixed by your merge. can you cut a release?

**Comment by pitbulk** [comment]
I will next week, I want to fix some issues before.

**Comment by vincentwoo** [comment]
@pitbulk ping
