### ISSUE TITLE
ruby-saml is missing support for canonicalization with comments

### ISSUE THREAD

**Issue by vincentwoo** [onelogin/ruby-saml#315]
I have a SAML response with `<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>` set.

ruby-saml uses:

```ruby
def canon_algorithm(element)
  algorithm = element
  if algorithm.is_a?(REXML::Element)
    algorithm = element.attribute('Algorithm').value
  end

  case algorithm
    when "http://www.w3.org/TR/2001/REC-xml-c14n-20010315" then Nokogiri::XML::XML_C14N_1_0
    when "http://www.w3.org/2006/12/xml-c14n11"            then Nokogiri::XML::XML_C14N_1_1
    else                                                        Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0
  end
end
```

which is obviously incorrect when parsing `http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments`.

Unfortunately it does not look like nokogiri supports "withComments" yet, but it would at least be "less incorrect" to choose `Nokogiri::XML::XML_C14N_1_0`

**Comment by vincentwoo** [comment]
@pitbulk your fix should probably also include "http://www.w3.org/2006/12/xml-c14n11#WithComments", no?

**Comment by vincentwoo** [comment]
ref: https://www.w3.org/TR/DSig-usage/

**Comment by pitbulk** [comment]
You are right
