### ISSUE TITLE
Gem release of latest master

### ISSUE THREAD

**Issue by vignesh-vs-in** [onelogin/ruby-saml#318]
It'd be great if we could get a gem v1.1.3 release with the latest master. So that we can depend on the gemfile to manage the dependencies.

**Comment by pitbulk** [comment]
I will release it, but I wanted to add some new features and fix some minor bugs before.
It will take 1 week to get that new release.

**Comment by vincentwoo** [comment]
Yo really think a new release should be cut. Critical fixes are in master but not latest release.

**Comment by pitbulk** [comment]
Done: https://rubygems.org/gems/ruby-saml/versions/1.2.0
