### ISSUE TITLE
The response was received at {recipient} instead of http://localhost:3000/saml/consume

### ISSUE THREAD

**Issue by archonic** [onelogin/ruby-saml#322]
I'm getting a response, but it's invalid. The error is 

```
The response was received at {recipient} instead of http://localhost:3000/saml/consume
```

Is `{recipient}` an unset `settings` attribute? I see no mention of it in any documentation I can find.

Sidenote: I noticed Ruby 2.0 isn't mentioned under supported versions. Is it actually unsupported or just untested?

**Comment by pitbulk** [comment]
```
The response was received at {recipient} instead of http://localhost:3000/saml/consume
```
This is a problem of the Identity Provider settings. What IdP are you using?

```
I noticed Ruby 2.0 isn't mentioned under supported versions. Is it actually unsupported or just untested?
``` 
Is supported.

**Comment by archonic** [comment]
I figured out the recipient field in the app settings on one login. I was looking for it in the code.

I suggest adding 2.0.x to the supported Ruby list. It current goes from 1.9.x to 2.1.x.

**Comment by pitbulk** [comment]
At https://rubygems.org/gems/ruby-saml/versions/1.1.2 you can read:
Required Ruby Version:  >= 1.8.7 

Also if you check the travis file, those environments are tested at CI.
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - ree
  - jruby-1.7.21
  - jruby-9.0.0.0

**Comment by omulmicsinegru** [comment]
Hello @archonic . I'm having the same issue you are . 

If you remember, can you please tell me what setting allowed you to set a recepient field? 
I've searched for it , but was unable to find it.

Thank you in advance for your help.

**Comment by tboyko** [comment]
@omulmicsinegru The recipient field can be set in OneLogin under the "Configuration" tab.
