### ISSUE TITLE
Empty audiences value gets read as {audience}

### ISSUE THREAD

**Issue by yookd** [onelogin/ruby-saml#325]
In our OneLogin console, we left "Audiences" empty, but set the issuer in our app to equal the issuer URL specified in the OneLogin console.

Since "Audiences" was left empty in the console, we expect `audiences.empty?` to return true [here](https://github.com/onelogin/ruby-saml/blob/v1.0.0/lib/onelogin/ruby-saml/response.rb#L444) and validate the audience.  However, `audiences` [here](https://github.com/onelogin/ruby-saml/blob/v1.0.0/lib/onelogin/ruby-saml/response.rb#L247) returns `['{audience}']`.

In your [support page](https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector), "Audience" is not required.  Should 'Audience' still remain optional or is there a bug with parsing the XML node value?

**Comment by s01ipsist** [comment]
I'm seeing the same thing. I don't think it's a bug in the xml parser code. 

If you inspect `response.response`, you will probably see like I did `<saml:Audience>{audience}</saml:Audience>` so this is the actual response from OneLogin.

If this is the "expected" "blank" response then the validation should check for that. 

https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector
says that the Audience field would resemble a simple domain. If I configure my Audience to be `"#{my_domain}"` that doesn't pass this `validate_audience` test either in my case as my `settings.issuer` is ``"#{my_domain}/saml/metadata"` as recommended in this project's README.

I ended up configuring Audience to `"#{my_domain}/saml/metadata"` to get past this, but something, code or documentation is not right.

**Comment by yookd** [comment]
@s01ipsist that's exactly what we ended up doing (`settings.issuer` and audience to `"#{domain}/saml/metadata"`)

**Comment by s01ipsist** [comment]
along the same lines, I had to configure Recipient to be
`"#{domain}/saml/consume"
as, when blank, it comes through as `{recipient}`

**Comment by pitbulk** [comment]
You may set the audience on the connector to interact with the ruby-saml

**Comment by s01ipsist** [comment]
@pitbulk I'm not sure I understand. 

After configuring the app: SAML Test Connector (IdP) `https://admin.us.onelogin.com/apps/XXXX/edit/#configuration`.

And then triggering a call to my `/consume` endpoint.
Is `{recipient}` the expected value for `audiences` when Recipient is left blank?
Is `{audience}` the expected value for `destination` when Audience is left blank?

I don't know enough to say it's wrong, it just seems unexpected or a bit strange.

**Comment by pitbulk** [comment]
This is how currently the SAML Test Connector (IdP) works. It inject those values when you left the fields blank.

I reported that issue since I think is better to not provide in the SAMLResponse a Recipient or Audience element if not provided in the form instead of {recipient} and {audience}.

But meanwhile please set as Recipient field the SP ACS URL endpoint value and as Audiente the SP entity ID
