### ISSUE TITLE
multiple ConsumerService endpoints

### ISSUE THREAD

**Issue by lisovskyvlad** [onelogin/ruby-saml#327]
So, looks like it is possible with saml  to have multiple AssertionConsumerService in metadata.

My case is that I would like to have one endpoint for testing purpose(I am Sp) and that IdP (shibboleth, sorry, not my choise) and another for production.

What do you think?

**Comment by pitbulk** [comment]
Hi @lisovskyvlad 

Currently our toolkit only supports one AssertionConsumerService URL.

My suggestion: define 2 SP entities (you only need to dynamically change the setting data), so you will have 2 metadatas to be registered at the IdP.

Imagine you have prod.sp.com and test.sp.com running the same piece of code, in this case lets assume you are using the [ruby-saml-example](https://github.com/onelogin/ruby-saml-example).
The [get_url_base](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L125) method will take care of the different url_base.
It will [build the  ruby-saml settings](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L9) based on that value
```
settings = Account.get_saml_settings(get_url_base)
```

[SP data will be built dinamically](https://github.com/onelogin/ruby-saml-example/blob/master/app/models/account.rb#L14) but [IdP data](https://github.com/onelogin/ruby-saml-example/blob/master/app/models/account.rb#L19) will be the same (Shibboleth IdP metadata).

**Comment by lisovskyvlad** [comment]
Hey @pitbulk,

thanks for quick answer, yeah, I have this approach with dynamic metadata (dep. of host) generating, but looks like IdP is not so flexible (but I am not sure) and they (IT consultant of if;))) have to chane this settings because of flexibility.

Anyway, thanks. What is about patch (I could try to write one) for this possibility? The goal is that metadata has possibility to have few ACS node. 
May be it is not needed for onelogin IdP service, but it fulfils saml 2.0 spec, so.

**Comment by pitbulk** [comment]
At the IdP-initiaited SSO flow, always the default ACS will be used
At the Sp-initiated SSO flow you will need to inform to the  IdP what ACS should be used (set a AssertionConsumerServiceURL parameter of the AuthNRequest).

Write a patch to support that is not really complex, but will increase the complexity of the toolkit.
My philosophy when implementing the OneLogin's SAML toolkit is to keep them simply, toolkits will work for the 95% of the cases, there are some scenarios like yours where the toolkit does not match exactly your needs, but you can extend anytime the classes and implement your own customization.

**Comment by joshpfosi** [comment]
I actually am having the identical issue. My IT department has solved this issue historically (using OneLogin's Java toolkit for example) by using the `assertion_consumer_service_index` metadata field with matching entity IDs for the different deployment environments (e.g. dev, beta, staging, prod). I think adding this field as a setting option will both solve this issue and bring this toolkit inline with the functionality of the other versions OneLogin supports.

**Comment by joshpfosi** [comment]
I am working on a PR for this idea now.

**Comment by pitbulk** [comment]
Read #328
