### ISSUE TITLE
IdpMetadataParser#parse method says it receives an Hash, but uses it as a Settings object

### ISSUE THREAD

**Issue by sanderhahn** [onelogin/ruby-saml#330]
`IdpMetadataParser#parse` method says it receives an Hash, however the code seems to use the options as an `Settings` object: https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L45
Changing the code into: `OneLogin::RubySaml::Settings.new(options[:settings] || {}).tap do |settings|` would make the code work like the @param says.

**Comment by sanderhahn** [comment]
Might have been misreading the docs, this maybe a non-issue.

**Comment by pitbulk** [comment]
Solved at:
- [Allow multiple authn_context_decl_ref in settings](https://github.com/onelogin/ruby-saml/commit/63e4b7a4e342fe9fb541a2cba634c718ed44f85f)
- [Allow options[:settings] to be an hash for Settings overrides in IdpMetadataParser#parse](https://github.com/onelogin/ruby-saml/commit/4616771ee06b2f3b42c3d74b4b23755b5d2f84cc)
- [include vendor folder on SimpleCov filters](https://github.com/onelogin/ruby-saml/commit/4fb48d692567d6391b6e326989edb3a486978c6b)
