### ISSUE TITLE
Version 1.3.1 has no tag or release on GitHub

### ISSUE THREAD

**Issue by md5** [onelogin/ruby-saml#343]
I noticed that there is a version 1.3.1 of `ruby-saml` on RubyGems.org, yet it does not have a tag or a release here on GitHub.

Can someone explain the difference between 1.3.0 and 1.3.1?

**Comment by pitbulk** [comment]
I added accidentally a test on the ruby-saml gem 1.3.0, so I released a new gem 1.3.1 without this test.
See https://github.com/onelogin/ruby-saml/issues/338

**Comment by md5** [comment]
Any chance you could tag it here?

**Comment by pitbulk** [comment]
Done: https://github.com/onelogin/ruby-saml/releases/tag/1.3.1
