### ISSUE TITLE
Private key w/ passphrase

### ISSUE THREAD

**Issue by jnfeinstein** [onelogin/ruby-saml#348]
Please excuse naivety if exists...

I am considering using a `OpenSSL::PKey::RSA` private key stored in a db, and would therefore like to encrypt the private key using the available cipher+passphrase variant of `to_pem`.  I believe the associated logic in this library is `Settings#get_sp_key` which first formats the private key and then constructs an `OpenSSL::PKey::RSA` object.

I do not see a setting for a passphrase nor the ability to pass in an object instead of a string (i.e. `settings.private_key = OpenSSL::PKey::RSA.new(encoded, passphrase)` and checking with `.is_a?(OpenSSL::PKey::RSA`).  Is the capability available and/or is there a reason why this would not be required for SSO/SAML?  I'll admit it has been challenging getting a handle of this protocol.

**Comment by pitbulk** [comment]
The toolkit does not support passphrase for private keys.
Is there a way to manipulate it from the database and obtain a clear private key to be used on the toolkit?

**Comment by jnfeinstein** [comment]
Thank you for the prompt reply, glad I was not missing anything.  I believe I can store an encoded PEM, then decode using passphrase and convert to PEM without passphrase in-memory.
