### ISSUE TITLE
Not able to install ruby-saml(1.3.0) in ruby 1.8.7 (rails 2.3.2 application)

### ISSUE THREAD

**Issue by santhoshcd** [onelogin/ruby-saml#349]
Hi

I am getting below error while installing ruby-saml(1.3.0) in my application(ruby 1.8.7,rails 2.3.2).

**Fetching: ruby-saml-1.3.0.gem (100%)**
**ERROR: Error installing ruby-saml:**
**mini_portile2 requires Ruby version >= 1.9.2.**

In gem list I can see the ruby-saml gem
gem li ruby-saml

**** LOCAL GEMS ****
**ruby-saml (1.3.0)**

I installed Mini portile gem
**mini_portile (0.6.2)**

I want to install ruby-saml(1.3.0) in ruby 1.8.7 because there are multiple functions(OneLogin::RubySaml::SloLogoutresponse,OneLogin::RubySaml::SloLogoutrequest) for idp initiated SLO, which are not in ruby-saml(0.7.2).

Question

1. Why I am getting above error?
2. Is there any problem without mini_profile2? 
    because mini_profile2 support 1.9+
3. Is there any other way to install ruby-saml(1.3.0) in ruby 1.8.7?

Please help

**Comment by pitbulk** [comment]
Duped issue:  https://github.com/onelogin/ruby-saml/issues/300

**Comment by santhoshcd** [comment]
Hi
   Thanks for the reply, I already installed nokogiri (1.5.10) and mini_portile (0.6.2) gem in my app still, I am getting  the same error(ERROR: Error installing ruby-saml:,mini_portile2 requires Ruby version >= 1.9.2.). Are there any other dependencies?
