### ISSUE TITLE
QUESTION: How do I access RelayState in the Response object

### ISSUE THREAD

**Issue by emarthinsen** [onelogin/ruby-saml#351]
RelayState gets passed back as a param. What's the best way to pull it out via the `OneLogin::RubySaml::Response` object?

**Comment by pitbulk** [comment]
I think you don't need to pass the RelayState parameter to your ``OneLogin::RubySaml::Response``.

After [validate it](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L24), retrieve the [NamrID](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L25) and the [attributes](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L26) and then log the user. 

After that check for the RelayState parameter (retrieve it directly from the ). If there is no parameter redirect the user to the default flow, if not, check if the URL of the RelayState is valid and redirect the user there/retrieve session State.

**Comment by emarthinsen** [comment]
Oh, grabbing it from the HTTP params makes a ton of sense. Thanks for helping me with that.
