### ISSUE TITLE
Response#issuers method was removed

### ISSUE THREAD

**Issue by adamstegman** [onelogin/ruby-saml#359]
b5c6c4d removed the `OneLogin::RubySaml::Response#issuers` method and inlined it in `#validate_issuer` instead.

We were depending on this method in apokalipto/devise_saml_authenticatable for multi-IdP support. Why was it removed? Should we re-implement it ourselves or can it be put back?

**Comment by pitbulk** [comment]
I will implement a different approach and maintain the issuers method.

**Comment by pitbulk** [comment]
@adamstegman can you review if you experience any issue with the new 1.4.1 release.

**Comment by GregMacdonald** [comment]
I had the same problem and it is resolved for me by 1.4.1

**Comment by adamstegman** [comment]
Great, seems like that works just fine! 👏 I'll have to wait and see if any issue reports come in from people actually using multiple IdPs, but our tests pass.
