### ISSUE TITLE
ruby-salm as idp

### ISSUE THREAD

**Issue by nqtien310** [onelogin/ruby-saml#360]
not really an issue. so I wanna to implement my app as IDP and I came across this gem `saml_idp`. Is it right that `ruby-saml` is just an implementation for SP and `saml_idp` is for IDP?

**Comment by pitbulk** [comment]
ruby-saml cover SP functionality.

We are not implementing an open source ruby IdP since we commercialize an [Identity as a Service platform](https://www.onelogin.com/product) (IDaaS).

I'm not familiar with open source IdP implementation on ruby so I can't help here.

**Comment by nqtien310** [comment]
Thanks @pitbulk.
