### ISSUE TITLE
Support multiple attribute values per attribute

### ISSUE THREAD

**Issue by jondavidjohn** [onelogin/ruby-saml#362]
In an example SAML AttributeStatement found [here](https://en.wikipedia.org/wiki/SAML_2.0#SAML_2.0_Assertions), the point of providing AttributeValue is to provide the IDP options for input in the associated attribute.

This gem does not currently support supplying multiple AttributeValue elements for a given Attribute.  Doesn't this actually mean the IDP could only provide a single value for this attribute, mostly rendering it useless?

```xml
   <saml:AttributeStatement>
     <saml:Attribute
       xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500"
       x500:Encoding="LDAP"
       NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
       Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.1"
       FriendlyName="eduPersonAffiliation">
       <saml:AttributeValue
         xsi:type="xs:string">member</saml:AttributeValue>
       <saml:AttributeValue
         xsi:type="xs:string">staff</saml:AttributeValue>
     </saml:Attribute>
   </saml:AttributeStatement>
```

Is there currently a way to accept multiple values per attribute? if not, would there be interest in a pull request to allow the `attribute_value` property to accept an array of values?

For example...

```ruby
      settings.attributes_index = 0
      settings.attribute_consuming_service.configure do
        service_name "Service"
        service_index 0
        add_attribute(
          name: "urn:oid:1.3.6.1.4.1.5923.1.1.1.1",
          name_format: "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
          friendly_name: "eduPersonAffiliation"
          attribute_value: ["member", "staff"]
        )
      end
```

**Comment by pitbulk** [comment]
> This  gem does not currently support supplying multiple AttributeValue elements for a given Attribute. 

We [take all the values](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L156), you can see that [test](https://github.com/onelogin/ruby-saml/blob/master/test/response_test.rb#L1008) where the toolkit extracts multiple values.

Have you read the [Retrieving Attributes](https://github.com/onelogin/ruby-saml#retrieving-attributes) section of the documentation?

Instead
```
response.attributes[:eduPersonAffiliation]   
#or
response.attributes.single(:eduPersonAffiliation)
```
use
```
response.attributes.multi(:eduPersonAffiliation)
```

**Comment by jondavidjohn** [comment]
Sorry 😕  was confused myself about how this all works (new to SAML).  I realize now that this is for IDPs sending multiple values.

Is there a way to communicate (as an SP) to IDP implementors

1) The acceptable values for a given attribute?
2) Validation failures on said attributes?

**Comment by pitbulk** [comment]
1) At the [AttributeConsumingService](http://www.datypic.com/sc/saml2/e-md_AttributeConsumingService.html) you can define [RequestedAttribute](http://www.datypic.com/sc/saml2/e-md_RequestedAttribute.html) elements with AttributeValue.
2) I think SAML standard does not cover it.

[Metadata for the OASIS SecurityAssertion Markup Language](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf)
```
2.4.4.2 Element <RequestedAttribute>

The <RequestedAttribute> element specifies a service provider's interest in a specific SAML attribute, optionally including specific values. Its RequestedAttributeType complex type extends the saml:AttributeType  with the following attribute:
isRequired  [Optional]
Optional XML  attribute indicates if the service requires the corresponding SAML attribute in order
to function at all (as opposed to me rely finding an attribute useful or desirable).

If specific <saml:AttributeValue> elements are included, then only matching values are relevant to
the service
```

Right now ruby-saml support 1), but you only are able to define [1 value for the attribute](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/attribute_service.rb#L49), if you want to contribute and improve it in order to support a list, a PR is welcome.

**Comment by jondavidjohn** [comment]
If I were to make a PR, would you see it reasonable to optionally accept an array as the `attribute_value`?

**Comment by pitbulk** [comment]
Yes sure, that is what I suggested. Extend the current paramter to support also an array.

**Comment by jondavidjohn** [comment]
@pitbulk to which branch should I submit my PR?

**Comment by pitbulk** [comment]
master
