### ISSUE TITLE
What is the purpose of settings.idp_entity_id?

### ISSUE THREAD

**Issue by raphaelcm** [onelogin/ruby-saml#364]
I can't figure out what it maps to in the SAML Specification: https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf

**Comment by pitbulk** [comment]
idp_entity_id --> IdP EntityID.

```
An <EntityDescriptor> represents a system entity in metadata, which is a SAML service, such
as an IdP or an SP. Each entity has an entityID, that is a unique name that distinguishes it from
any other entity.
6/10 2014-01-08
The value of the entityID attribute SHOULD be the canonical URL of the entity's metadata
document. Canonical URLs follow the semantic-preserving normalization as specified in RFC
3986 section 6. The entity ID should accurately reflects the organization that owns the entity.
```

Reference: https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf


We use it on the ruby-saml to validate the Issuer value of the SAMLResponses.

**Comment by raphaelcm** [comment]
So then what is the purpose of `settings.issuer`?

**Comment by pre** [comment]
`settings.issuer` is now deprecated and one should use `settings.sp_entity_id` instead. The new method name should make sense intuitively.
