### ISSUE TITLE
ruby-saml 1.4.1 release is not tagged in Github

### ISSUE THREAD

**Issue by irvingreid** [onelogin/ruby-saml#366]
The 1.4.1 release is mentioned in changelog.md and available on RubyGems (https://rubygems.org/gems/ruby-saml/versions/1.4.1), but is not listed in https://github.com/onelogin/ruby-saml/releases.

**Comment by pitbulk** [comment]
Thanks for reporting that.

Now is available:
https://github.com/onelogin/ruby-saml/releases/tag/1.4.1
