### ISSUE TITLE
Any plans to release v1.4.2?

### ISSUE THREAD

**Issue by acreeger** [onelogin/ruby-saml#370]
I was wondering if there is any plan to release v1.4.2 with some of the recent changes?

Thanks for all your hard work on this gem.

**Comment by pitbulk** [comment]
As you requested it, I will publish a new version soon.

**Comment by acreeger** [comment]
Thank you!

**Comment by acreeger** [comment]
Also, I noticed that 1.3.0 is the last tag. Is that intentional?

**Comment by pitbulk** [comment]
1.3.0 isn't the last tag...

- [1.4.1](https://github.com/onelogin/ruby-saml/releases/tag/1.4.1)
- [1.4.0]((https://github.com/onelogin/ruby-saml/releases/tag/1.4.0)
- [1.3.1]((https://github.com/onelogin/ruby-saml/releases/tag/1.3.1)

**Comment by pitbulk** [comment]
Here is the release:
* Github: https://github.com/onelogin/ruby-saml/releases/tag/1.4.2
* Rubygems: https://rubygems.org/gems/ruby-saml/versions/1.4.2
