### ISSUE TITLE
SamlReponse only supports one level of StatusCode

### ISSUE THREAD

**Issue by reggieb** [onelogin/ruby-saml#374]
SAML supports [two levels of StatusCode](https://docops.ca.com/ca-api-gateway/8-3/en/policy-assertions/assertion-palette/message-validation-transformation-assertions/set-saml-response-status-code-assertion), and on failure it is the inner one that has the most pertinent information. For example, here is a NoAuthnContext failure:

```saml
  <saml2p:Status xsi:type="saml2p:StatusType">
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder" xsi:type="saml2p:StatusCodeType">
      <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext" xsi:type="saml2p:StatusCodeType"/>
    </saml2p:StatusCode>
  </saml2p:Status>
```

However the method `OneLogin::RubySaml::Response#status_code` will only output if there is just one StatusCode:

```ruby
def status_code
    @status_code ||= begin
      nodes = REXML::XPath.match(
        document,
        "/p:Response/p:Status/p:StatusCode",
        { "p" => PROTOCOL }
      )
      if nodes.size == 1
        node = nodes[0]
        node.attributes["Value"] if node && node.attributes
      end
   end
 end
```

Could this be replaced with something that either returned an array of statuses or concatenated multiple statuses. For example:

```ruby
def status_code
  @status_code ||= begin
     nodes = REXML::XPath.match(
        document,
        "/p:Response/p:Status//p:StatusCode",
        { "p" => PROTOCOL }
      )
      statuses = nodes.collect do |node|
        value = node.attributes["Value"]
        value.split(':').last
      end
      statuses.join(" : ")
  end
end
```

**Comment by pitbulk** [comment]
Sure, are you able to provide the PR with that change and unit test?

**Comment by reggieb** [comment]
Hi @pitbulk, I hadn't spotted that you'd responded to this issue. 

I don't have a problem creating a PR, but the [PR I've currently have in place](https://github.com/onelogin/ruby-saml/pull/373) seems to be failing a CI test due to what looks like a nokogiri version issue in JRuby. I think if I submit another PR it will have the same issue.

**Comment by pitbulk** [comment]
you can send that PR... it seems that in JRuby sometimes there are random false failing CI test

**Comment by pitbulk** [comment]
any progress?

**Comment by reggieb** [comment]
Sorry - I've moved to another project, and we managed to work around the problem in [the project](https://identityassurance.blog.gov.uk/2017/02/13/using-gov-uk-verify-to-transform-a-local-authority-service/) where the fix was required.

However, I should be able to get this into a PR (especially now that my other PR is progressing), so at the moment it is a case of finding the time to write it.
