### ISSUE TITLE
idp_metadata_parser not parsing correct idp_cert from metadata

### ISSUE THREAD

**Issue by angelicas** [onelogin/ruby-saml#375]
The method certificate_base64 method here: https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L186-L203, which populates the idp_cert of the settings is not parsing the correct x509 cert. This is causing the saml_response object to be invalid. So when I run saml_response.is_valid? I get ["Invalid Signature on SAML Response"]. There are many x509s (appx 20) in my customer's xml who is using ADFS. Has anyone else come across this issue? Are any updates being made to improve this parsing? Thanks in advance! :)

**Comment by pitbulk** [comment]
Right now the parser extracts the first x509certificate found.

**Comment by angelicas** [comment]
Referencing new comment I made here: https://github.com/onelogin/ruby-saml/issues/329

**Comment by angelicas** [comment]
Ah I see. Ok I guess I'll have to monkey patch a workaround. Thanks.
