### ISSUE TITLE
NoMethodError: undefined method `empty?' for #<OpenSSL::PKey::RSA:0x5d6ed9cb>

### ISSUE THREAD

**Issue by prcongithub** [onelogin/ruby-saml#378]
Getting following error when ```metadata_signed``` is set to true.
```
NoMethodError: undefined method `empty?' for #<OpenSSL::PKey::RSA:0x5d6ed9cb>
	from /home/jombay/.rvm/gems/jruby-1.7.4/gems/ruby-saml-1.0.0/lib/onelogin/ruby-saml/settings.rb:137:in `get_sp_key'
	from /home/jombay/.rvm/gems/jruby-1.7.4/gems/ruby-saml-1.0.0/lib/onelogin/ruby-saml/metadata.rb:107:in `generate'
```
Any ideas?

**Comment by pitbulk** [comment]
At the generate method of metadata, toolkit [get the private key from the settings](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb#L111) using the [get_sp_key](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L138) method. 

The expected value for the private_key of the settings is to be [a string](https://github.com/onelogin/ruby-saml#signing). In your case, it seems that you assignd directly a OpenSSL::PKey::RSA object, that does not contain empty? method.  Review your settings.

**Comment by prcongithub** [comment]
Thanks @pitbulk. My bad!
