### ISSUE TITLE
Any examples of handing SAML and custom logins?

### ISSUE THREAD

**Issue by gitleet** [onelogin/ruby-saml#381]
I want to provide my users with the option of using SAML, but the default way they will be signing up and logging into my application will be a custom Rails authentication system.

When using SAML and the user authenticates, do I just then create the regular authentication token and save it to a cookie to fetch the user from my database?  I guess the first time I will somehow pull  certain information provided by SAML like firstname/lastname and email?

**Comment by archonic** [comment]
When using Devise and SAML, you just have two ways into the application - through the Devise sessions controller and through a SAML controller. Both use the `sign_in` method if everything goes well. You should be able to follow this example SAML controller and replace any Devise references with your own authentication methods. https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb
