### ISSUE TITLE
Creating Logoutrequest with multiple sessionindex entries(IDP initiated SLO)

### ISSUE THREAD

**Issue by arminak89** [onelogin/ruby-saml#384]
As part of the IDP implementation, I want to create logout requests with multiple session index entries. Does ruby-saml support this functionality?

**Comment by pitbulk** [comment]
Right now only 1 session index per request, but you could fork and customize it
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/logoutrequest.rb#L115
