### ISSUE TITLE
Generated SamlRequest doesn't Base64 decode properly

### ISSUE THREAD

**Issue by bjm88** [onelogin/ruby-saml#394]
Hi- I am logging the result of
saml_request = OneLogin::RubySaml::Authrequest.new
xml_req = saml_request.create(@saml_settings, extra_params)

our sample settings are basic, no encryption or special use cases.  The full response is like such
https://testidp.someSamlIdp.com/sso?SAMLRequest=pZNBj9owEIX%2FSm4%2BJcYQFrAIUgSqhLRtEWx72MvK6wys1cROPeNu%2Bu%2FrBGg57O6lp0jj5%2FnevHGWqJq6lWWgF7uHnwGQkhIRPBln185iaMAfwP8yGr7t7wv2QtSi5BxBBw%2BZVh4q12XaNTLPJ9z509PJu9ByMZmMeYidkPcMji3X534sKYm8eQ4EZ4KxpwtiayvoCjZlySY6MVb1Nv5BTRtxlrJGEYYfYpwF5OtY2rjucPjKEV2msO1Yst0U7Kla5CKfwiSdPefjNJ%2Brebq4Ox7TyUwvcq0Wo3keQVvEELlIylLBxiMxS0fTVIgHcSenuRyJR5Z8j1MMRsbZiCVdU1uU%2FVAFC95Kp9CgtKoBlKTlofx8L6NQqmuOt1faj%2B%2B03pHTrmarZa%2BWgzu%2F%2Bp%2FUGyBVKVJLfttxeV78l%2Bhgu9m52ujfSVnX7nXtQREUjHyIm%2FrkfAz7fc8iE0PFVOlxkMpgsQVtjgYqxq%2BYy9OCanhocesEHSVr18SFGuyThU5puk59q1rXMcc9HFcfRq2l7nWxvIufV%2BerXUwSdEQ%2BeBUtOU%2BXAN5sfj57x%2Bjf09vfZPUH&providerId=blah

As you can see the SAMLRequest variable will not Base64 decode properly, even if I first "unescape" the http parameter....

Is it expected this is Bsae64 encoded, it looked like it...I was expecting to decode and see an xml document like structure of the SAML....

**Comment by pitbulk** [comment]
An AuthNRequest on the HTTP-Redirect binding is first deflate and then base64 encoded... later urlencoded.

So if you copy that SAMLRequest value, [urldecode it](https://www.samltool.com/url.php) and later [base64 decode + inflate](https://www.samltool.com/decode.php) you will get:

```
<samlp:AuthnRequest xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceURL="https://secure.caredox.com:443/org_group/1332/users/saml/sp/consume" AttributeConsumingServiceIndex="5" Destination="https://iparent.matsuk12.us/CareDoxSSO/sso.aspx" ID="_d94145e3-7b42-48a8-96ff-37c94ca90845" IssueInstant="2017-05-11T16:54:01Z" Version="2.0">
  <saml:Issuer>https://secure.caredox.com:443/org_group/1332/users/saml/sp/metadata</saml:Issuer>
  <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/>
  <samlp:RequestedAuthnContext Comparison="exact">    <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>```

**Comment by bjm88** [comment]
Thank you!  worked perfectly!  I was following the code and it looked like compression was only done if passed as a flag true in settings, I guess I missed somewhere that is the default behavior.
