### ISSUE TITLE
undefined method `gsub' when parsing response

### ISSUE THREAD

**Issue by jesmith17** [onelogin/ruby-saml#403]
I am parsing SAML token and am getting the following error when in my code. 

```bash
NoMethodError (undefined method `gsub' for #<ActionController::Parameters:0x007fb937d71598>):
```

The code being executed is 

```ruby
 idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new

    settings = idp_metadata_parser.parse_remote('https://testclient.com/SSO-Metadata.xml')
    settings.assertion_consumer_service_url = 'http://localhost:3000/sso/consume'
    response = OneLogin::RubySaml::Response.new(params[:Response], :settings => settings)
```

It appears that the Response.new command is expecting a string, and not an ActionController::Parameters object which is a bit of a surprise as that would be the default object to come back in a call to `params[:Response]` or `params[:SAMLResponse]` like is shown in the examples. 

Do I essentially need to take the XML I get back and turn it into one very long string object to hand to the Response.new command, or is there something else that I am missing here?

Ruby 2.3.1
Rails 5.0.3
Ruby-Saml 1.4.3
Mac OSX

**Comment by pitbulk** [comment]
At [ruby-saml example](https://github.com/onelogin/ruby-saml-example) I have the [following code](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L22):
```
response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], :settings => settings)
```
and it works for previous versions of Rails (Rails 4).

Maybe failing on Rails 5 where as you suggested, have to convert the parameter into a string.
