### ISSUE TITLE
NoMethodError from IdpMetadataParser#parse_to_hash

### ISSUE THREAD

**Issue by jacobwalkr** [onelogin/ruby-saml#406]
I have the following two lines in my Devise initializer, trying to set up with [TestShib](https://www.testshib.org/):

```ruby
idp_meta_parser = OneLogin::RubySaml::IdpMetadataParser.new
idp_meta = idp_meta_parser.parse_remote_to_hash('https://www.testshib.org/cgi-bin/sp2config.cgi?dist=Others&hostname=localhost')
```

When run, the second line throws a `NoMethodError`:

```
rails aborted!
NoMethodError: undefined method `attributes' for nil:NilClass
/home/jacob/Code/DentalRadiography/config/initializers/devise.rb:261:in `block in <top (required)>'
/home/jacob/Code/DentalRadiography/config/initializers/devise.rb:3:in `<top (required)>'
/home/jacob/Code/DentalRadiography/config/environment.rb:5:in `<top (required)>'
/home/jacob/Code/DentalRadiography/bin/rails:4:in `require'
/home/jacob/Code/DentalRadiography/bin/rails:4:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

I get the same error running it through IRB and when loading the XML file as a string with `File#load` and `IdpMetadataParser#parse_to_hash`.

Am I missing something? I can't figure this one out. Thanks :)

**Comment by pitbulk** [comment]
what ruby-saml version are you using?

parse_remote_to_hash method was introduced on [ruby-saml 1.4.3](https://github.com/onelogin/ruby-saml/releases/tag/1.4.3).

**Comment by jacobwalkr** [comment]
Oh yeah, sorry: ruby-saml 1.4.3

**Comment by pitbulk** [comment]
The info published at: https://www.testshib.org/cgi-bin/sp2config.cgi?dist=Others&hostname=localhost
is not IdP metadata XML, instead you should use:   https://idp.testshib.org/idp/shibboleth

**Comment by jacobwalkr** [comment]
Oh. Just being thick then! Thanks a lot :)
