### ISSUE TITLE
idp_multi_cert nil if only multiple signing certs in metadata in 1.4.3

### ISSUE THREAD

**Issue by bheeshmar** [onelogin/ruby-saml#412]
I have a metadata file from an Azure AD instance which has 3 "signing" certs but no "encryption" certs. When I parse this with the `IdpMetadataParser` I get the first signing cert in the `idp_cert` field, but a nil in `idp_cert_multi` instead of the 3 certs I expect.

I believe the root cause is the `certificates.size == 1 ||` condition in [#merge_certificates_into](https://github.com/onelogin/ruby-saml/blob/1.4.3/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L319), which I think can be safely eliminated.

Alternatively, perhaps initializing `certs = {signing: [], encryption: []}` in [#certificates](https://github.com/onelogin/ruby-saml/blob/1.4.3/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L264) would also help (and properly return symbolized keys).

**Comment by pitbulk** [comment]
@bheeshmar 
Are you using master with recent changes?
https://github.com/onelogin/ruby-saml/pull/410

**Comment by bheeshmar** [comment]
@pitbulk No, I'm running 1.4.3 and using omniauth-saml. I worked around the symbolized keys problem for now, but the bigger issue is the lack of `idp_cert_multi` support when there are only signing KeyDescriptors.

**Comment by pitbulk** [comment]
I will do a new release soon and review idp_cert_multi support

**Comment by bheeshmar** [comment]
Thanks! Looking forward to it and thanks for all the hard work!

**Comment by thiago-sydow** [comment]
Having this issue too, glad to see that the fix is not far away to be released. Thanks. 👍

**Comment by bheeshmar** [comment]
One more issue around `idp_cert_multi` support: `Response#validate_response_state` only checks `idp_cert` and `idp_cert_fingerprint` from settings - it doesn't consider `idp_cert_multi` which when set, does not set either of those fields.

**Comment by pitbulk** [comment]
I will release it today.

**Comment by pitbulk** [comment]
Released 1.5.0
