### ISSUE TITLE
Unclear Exception Message Wording

### ISSUE THREAD

**Issue by omgitsbillryan** [onelogin/ruby-saml#413]
https://github.com/onelogin/ruby-saml/blob/e9d454b5bf1d203c53fd008a7c2200aff9e4f7d6/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L106

I _think_ this is supposed to read:

> idp_metadata ~~may~~ **must** contain an IDPSSODescriptor element

**Comment by pitbulk** [comment]
do you have a PR?
