### ISSUE TITLE
redirect_to [created request] preflight response is invalid

### ISSUE THREAD

**Issue by ravishwetha** [onelogin/ruby-saml#415]
def init
    request = OneLogin::RubySaml::Authrequest.new
    redirect_to(request.create(saml_settings))
end

Adding this block to my saml_controller, I get the error: 

Failed to load https://.../trust/saml2/http-post/sso/...: Response for preflight is invalid (redirect)
However following the link generated from request.create(saml_settings) allows me to log in. Is there a better way to initiate the request?

**Comment by pitbulk** [comment]
That the normal way to execute SP-initiaited SSO as you can see [here](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L16)

**Comment by ravishwetha** [comment]
I understand, then would there be a way to use this without encountering the preflight is invalid error?

**Comment by pitbulk** [comment]
I never saw that error before. It doesn't seem an error related with ruby-saml but instead with the framework you are using.

**Comment by ravishwetha** [comment]
Alright then, thanks. It seems that most browsers don't follow the 302 redirect I receive: https://stackoverflow.com/questions/28917489/http-302-redirect-to-a-cors-request-is-dropped-by-browsers. But then I assume receiving that is not normal and unrelated to ruby-saml yes?
