### ISSUE TITLE
AttributeValues are required to be strings for Metadata

### ISSUE THREAD

**Issue by jhubert** [onelogin/ruby-saml#416]
We came across this when updating the to latest version.

The metadata generation is [using `.to_str` to get the attribute value](https://github.com/onelogin/ruby-saml/blob/186e229e6b8015638a31c11ca700dcca318c2e28/lib/onelogin/ruby-saml/metadata.rb#L102). `to_str` is only defined on String values, which is throwing a 500 error for our configuration that has boolean attribute values.

This may be the intended behavior, and perhaps we should always be using a string but I wanted to check.

Our configuration has a line like this:

```ruby
settings.attribute_consuming_service.configure do
  ...
  add_attribute({ name: 'is_active', name_format: NAME_FORMAT, friendly_name: 'Is Active?', attribute_value: true })
end
```

This line causes a 500 error because `attribute_value` is boolean, even though `true.to_s` would work just fine and convert `true` to `"true"`.

Personally, I like the way it reads being a boolean value and it allows an easy way to support methods that return boolean responses like this:

```ruby
add_attribute({ name: 'is_active', name_format: NAME_FORMAT, friendly_name: 'Is Active?', attribute_value: default_user_active_setting })
```

The impact of using `.to_s` vs `.to_str` seems very minimal, but I'd love to know if there is a more complicated reason for the choice.

If there isn't, I'm happy to submit a PR.

**Comment by pitbulk** [comment]
There is no reason, please provide a PR with the change and some test to cover the new behavior and I will be happy to merge ;).
