### ISSUE TITLE
Is it possible to run this on an app behind a VPN?

### ISSUE THREAD

**Issue by dmerrick** [onelogin/ruby-saml#419]
Possible noob question here:

We have an app running in a private VPC on AWS. It is only accessible to clients connected to our VPN.

I believe that SAML requires a callback from the SSO provider (in our case Google) to the app, so is it possible to use this in our situation? Or would we have to set up some sort of proxy or something in order to make the connection to our private app.

**Comment by pitbulk** [comment]
As far as the user that do the SSO has access to the VPN, the SAML integration will work.

(on ruby-saml, SAML happens on user browser, is front-channel not back-channel).

**Comment by dmerrick** [comment]
Thank you!
