### ISSUE TITLE
Signature Algorithm is Incorrect: Returning sha1 instead of sha256

### ISSUE THREAD

**Issue by mcollie1** [onelogin/ruby-saml#429]
In the xml document, the Signature Method and Digest Method are as follows:

`<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>`
`<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>`

However, the Ruby-Saml gem parses the data as follows:

`:digest_method=>"http://www.w3.org/2000/09/xmldsig#sha1", `
`:signature_method=>"http://www.w3.org/2000/09/xmldsig#rsa-sha1"`

The Ruby-Saml parser's SHA response is incorrect. It should be sha256 instead of sha1. 

Do you know if there's a quick fix for this?

version 1.6

**Comment by pitbulk** [comment]
Sorry, I don't get what you train to explain, can you detail what are you trying to parse and what method fails to parse it?

**Comment by mcollie1** [comment]
I'm parsing an idp metadata file, and I'm using the `.parse_remote` or `.parse` methods (depending on if the input is a url or file). 

Within the metadata files, the `ds` tags above are present, with the `sha` that I want to extract. However, the `parse_remote` and `parse` methods are returning the default sha, `sha1` instead of `sha256`.

**Comment by pitbulk** [comment]
Please provide an XML example (replace real domain by example.com if you want, so I can debug and fix.

**Comment by mcollie1** [comment]
I'm able to post XML immediately as there's a lot of identifiers in there. However, here's an extract from the file.

```<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <ds:Reference URI="#_cd18e5-a314-c6ccec89c270">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <ds:DigestValue>xS/T7pT8Y/B9wycQf4Nx/U6eoI9I3L9jrlk=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
```

I expect `settings.security[:signature_method]` to return `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`. instead, it returns a string with `sha1` at the end

**Comment by pitbulk** [comment]
That seems part of a Signature of the IdP's metadata. That shouldn't be related with SP signature algorithm, so I don't see why I should update settings.security[:signature_method] to use the same signature algorithm that the IdP has... can be different...
