### ISSUE TITLE
setting.issuer incompatibility with other IDPs

### ISSUE THREAD

**Issue by mkon** [onelogin/ruby-saml#430]
We are trying to integrate against Trustbuilder IDP and if I set `settings.issuer` to my own application, it will fail the`validate_name_id` validation.
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L783-L787
SPNameQualifier is the IDP, so it can not match my own application.

If I set issuer to the IDP, it will fail the `validate_audience`
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L599-L602

It seems issuer is expected to be two different values at the same time.

Seems to be related to #283

**Comment by pitbulk** [comment]
Understand the settings.issuer as the Service Provider entity ID, not the Issuer attribute of the SAMLResponse.

So in validate_name_id
name_id_spnamequalifier MUST match settings.issuer , the SP entityID.

**Comment by akshah123** [comment]
@pitbulk Why use issuer to check against audience in this case and not just allow an option for audience directly?

**Comment by pitbulk** [comment]
That is how it was when I started to maintain that toolkit.
