### ISSUE TITLE
Multiple SingleSignOnServiceBinding - can I specify which to use?

### ISSUE THREAD

**Issue by acontero** [onelogin/ruby-saml#435]
I have a question about the code here that is parsing the single sign on url which you will later assign to be the idp_sso_target_url in the settings object: https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L218. I'm not quite sure I understand how the it is prioritizing the bindings. In one of my customer's metadata files they list 3:

    <SingleSignOnService Binding='urn:mace:shibboleth:1.0:profiles:AuthnRequest' Location='https://shibboleth..../idp/profile/Shibboleth/SSO'/>
    <SingleSignOnService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' Location='https://shibboleth..../idp/profile/SAML2/POST/SSO'/>
    <SingleSignOnService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect' Location='https://shibboleth..../idp/profile/SAML2/Redirect/SSO'/>

It seems that the gem is storing the first one to be the idp_sso_target_url. This behavior, from what I can see, does not look like it has changed over the past couple of years. Yet it seems we used to hit the third url for our customer. My customer says their metadata has not changed, so I'm trying to figure out if this code has changed in behavior. Also, is there a way for me to specify which SingleSignOnService url or which binding to use?

Thanks!

**Comment by pitbulk** [comment]
The parser method accepts the following options:

 # @option options [Array<String>, nil] :sso_binding an ordered list of bindings to detect the single signon URL. The first binding in the list that is included in the metadata will be used.
 # @option options [Array<String>, nil] :slo_binding an ordered list of bindings to detect the single logout URL. The first binding in the list that is included in the metadata will be used.

As sso_binding / slo_binding you can provide a ordered list to detect the SSO and SLO urls.
The 1st found will be the one used.
 
The binding option was introduced in 2016 in  PR [298] and I don't think we changed its behavior.
