### ISSUE TITLE
Unable to get logging output from OneLogin:RubySaml::Logger

### ISSUE THREAD

**Issue by clader** [onelogin/ruby-saml#436]
Hi there.  I've tried to follow the instructions to get logging output to a custom file from the readme.  I've tried placing the following:
```ruby
OneLogin::RubySaml::Logging.logger = Logger.new(File.open('/var/log/ruby-saml.log', 'w'))
```

... in a rails initializer, or in  my rails environments file, or in the SAML application controller, but nothing seems to work.

I see the file getting created, but nothing is ever logged to it.  I currently have SAML logins using the gem working and I see log entries go to standard out, but am just unable to use this custom logging setting to divert saml logs to a file.  

Any help is appreciated.

(btw using 1.6 of the gem under rails5 with ruby 2.4.0)

**Comment by furuhama** [comment]
I got the same situation.

I changed intializer like a following line, and it may be solved this problem.

```ruby
OneLogin::RubySaml::Logging.logger = Logger.new('/var/log/ruby-saml.log')
```

(This would not be the problem from this gem, but from the usage of Ruby default logger.
ref: https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html#class-Logger-label-How+to+create+a+logger)
