### ISSUE TITLE
Missing details in errors

### ISSUE THREAD

**Issue by jnfeinstein** [onelogin/ruby-saml#439]
Good evening,

I recently encountered a response that had the following status:
```
<samlp:Status>
  <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester">
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy" />
  </samlp:StatusCode>
</samlp:Status>
```
I am dumping the errors as such:
```
response.errors.join("\n")
```
This resulted in:
```
The status code of the Response was not Success, was Requester
```
The additional information that the NameID was invalid would have been very helpful in debugging this customer's issue.

Is there a better way to dump the errors that would be more descriptive?

**Comment by pitbulk** [comment]
The extra_code information [is added ](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L223) and returned by the status_code method and [is used to build the error](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L399).

Maybe the there is an issue with the method [status_error_msg](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/utils.rb) method. Can you confirm?

**Comment by jnfeinstein** [comment]
Looks like this was added in 1.5.0 and we're using 1.3.1.  Confirmed working in 1.6.1.  Thanks for your assistance!
