### ISSUE TITLE
samltool.com returning errors when validating AuthnRequests

### ISSUE THREAD

**Issue by soupmatt** [onelogin/ruby-saml#463]
I couldn't find a way to submit a onelogin support ticket without being a customer, so I'm opening a ticket here. I was trying to validate a AuthnRequest using https://www.samltool.com/validate_authn_req.php. No matter what I enter, it returns `Invalid array settings: idp_cert_or_fingerprint_not_found_and_required`. I saw that this issue was raised in onelogin/php-saml#298 a couple weeks ago, but it still hasn't been fixed.

**Comment by pitbulk** [comment]
Thanks for reporting it.

We were already aware. Fixed it but still not deployed patches on the server.
