### ISSUE TITLE
No possibility specify ResponseLocation for SingleLogoutService

### ISSUE THREAD

**Issue by rlazoryshchak** [onelogin/ruby-saml#467]
I couldn't find the way to specify `ResponseLocation` for `SingleLogoutService`. From tests both links the same:
```
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://hello.example.com/access/saml/logout" ResponseLocation="https://hello.example.com/access/saml/logout"/>
```
From the [code](https://github.com/onelogin/ruby-saml/blob/c6da73baefeec891c9e0ded91fb4b123a48ce0a7/lib/onelogin/ruby-saml/metadata.rb#L67) you can see that `ResponseLocation == Location`. Might `ResponseLocation` to be equal `assertion_consumer_logout_service_url`? Please correct me if I am wrong.

**Comment by pitbulk** [comment]
Its ok to have both endpoints Location and ResponseLocation as the same endpoint, and in that endpoint check if a LogoutRequest or a LogoutResponse was received.

See that [example](https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L45) that manages all the SLO scenarios (SLO SP initiated (send and receive), SLO initiated (receive and send),

**Comment by pitbulk** [comment]
And why is different? As I showed in the example, can be handled in a unique endpoint.

**Comment by rlazoryshchak** [comment]
Ok, will try to do as in example above. Thank you for help.
