### ISSUE TITLE
OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: nested asn1 error):

### ISSUE THREAD

**Issue by nunziofiore** [onelogin/ruby-saml#473]
It's all ok with that library but I have this error
`
OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: nested asn1 error):`

on Single Logout.
It seems that is when library read the private_key
```

formatted_private_key = OneLogin::RubySaml::Utils.format_private_key( *thestringwithkey* )
OpenSSL::PKey::RSA.new(formatted_private_key)
```

error is at OpenSSL::PKey::RSA.new 

Someone can help me? I don't understand the error!

**Comment by pitbulk** [comment]
How are you providing that Private key?

Can you try to copy the formatted_private_key, save it in a file and try to validate it with the openssl command?
```
openssl rsa -noout -text -in sp.key
```

**Comment by nunziofiore** [comment]
I found that it was a problem of passphrase. I didn't find in ruby-saml a way to pass the passphrase and also the Util formatter it seems to give a wrong data.
I can fix the problem like this: https://github.com/nunziofiore/ruby-saml/commit/6264bcf12d9536f739271baf3d93a9200d8c69a7

**Comment by pitbulk** [comment]
Yes, the toolkit is not able to manage private keys with a passphrase.

You can also remove the passphrase:
https://knowledge.digicert.com/solution/SO5292.html

At the end, having the private key encrypted, but the secret for unencrypting it in the same setting file is not far away than having the private key directly unencrypted,

**Comment by nunziofiore** [comment]
Ok great, I'll try that way. Thank you
