### ISSUE TITLE
Shibboleth logout issue

### ISSUE THREAD

**Issue by RohitVenturit** [onelogin/ruby-saml#476]
I am facing problem in logout 
 
here is snipped from code:
relayState =  url_for controller: 'saml', action: 'index'
redirect_to(logout_request.create(settings, :RelayState => relayState))

Here is the screenshot of the error.
<img width="1276" alt="screen shot 2018-10-23 at 2 54 35 pm" src="https://user-images.githubusercontent.com/40765501/47350911-8ce48f00-d6d4-11e8-83ec-c02bea9a86c5.png">

**Comment by pitbulk** [comment]
Is the Single logout Service value of the "Configuration" tab of the OneLogin's connector properly configured?

**Comment by RohitVenturit** [comment]
Yes, here is screenshot of configuration tab.

**Comment by pitbulk** [comment]
I found where the issue is.

What is wrong is the ruby-saml settings.

As the IdP single logout service value, you may set
```
https://rohit-india.com-dev.onelogin.com/trust/saml2/http-redirect/slo/846039
```

Right now you have a wrong value.

**Comment by RohitVenturit** [comment]
Tried. Did not worked. Same issue persist.

**Comment by pitbulk** [comment]
Can you export and send to my mail the SAML Tracer as well as screenshots of the SAML settings of OneLogin's connector and toolkit?

P.S My email is on my profile.
