### ISSUE TITLE
issue in redirecting back to SP

### ISSUE THREAD

**Issue by RohitVenturit** [onelogin/ruby-saml#477]
I am trying to redirect  back to SP from this code snippet of **sp_logout_request** method but user is stopping at https://app.onelogin.com/login.  Any issue here?

    relayState =  url_for controller: 'saml', action: 'index'
    redirect_to(logout_request.create(settings, :RelayState => relayState))

**Comment by pitbulk** [comment]
is that the same issue than
https://github.com/onelogin/ruby-saml/issues/477 ?

Please confirm.

**Comment by RohitVenturit** [comment]
plz check #477 again

**Comment by gkirill** [comment]
@pitbulk Yes, it is same issue. Because your link points to **this** issue.

**Comment by jseraf** [comment]
Did you mean #476 @pitbulk ?
