### ISSUE TITLE
ADFS with redirect problem (singleSignOnService)

### ISSUE THREAD

**Issue by aleonidas** [onelogin/ruby-saml#478]
I believe my problem is similar to what was reported in issue #276 . When redirecting to the ADFS URL, the URL structure is as follows:
`" ... /adfs/ls/idpinitiatedsignon.aspx?logintorp=mysystem&SAMLRequest=... "`

If I remove this `` & `` between my identifier and the `` SAMLRequest`` parameter, it works. However, if I simply change the "s" to lowercase, it works (`sAMLRequest`).

When debugging the problem, I had the following SAMLResponse:
```
Cache-Control:  no-cache,no-store
Pragma:  no-cache
Content-Length:  10266
Content-Type:  text/html; charset=utf-8
Expires:  -1
Server:  Microsoft-HTTPAPI/2.0
x-frame-options:  DENY
P3P:  ADFS doesn't have P3P policy, please contact your site's admin for more details
```

```
<samlp:AuthnRequest
    
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    
    ID="ONELOGIN_c13779ed7de3ab128640b708f1b77015e7fd54cb"
    
    Version="2.0"
    
    ProviderName="MyCompany"
    
    IssueInstant="2018-11-07T18:34:58Z"
    
    Destination="https://adfs.mycompany.com.br/adfs/ls/idpinitiatedsignon.aspx?
    logintorp=mysystem"
    
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    
    AssertionConsumerServiceURL="http://samlsp.mycompany.com.br/saml2/acs">
    <saml:Issuer>http://samlsp.mycompany.com.br/saml2/metadata</saml:Issuer>
    <samlp:NameIDPolicy
        
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
        
        AllowCreate="true" />
    <samlp:RequestedAuthnContext 
        Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

The problem is only when identifying the "`SAMLRequest`" parameter, which is handled by the package itself.

I did not find anything to help me about it.
Thank you very much in advance.

**Comment by pitbulk** [comment]
Maybe is related with the RequestedAuthnContext value.

Try set on settings:
settings.authn_context = nil
settings.authn_context_decl_ref = nil

**Comment by aleonidas** [comment]
I'm still not sure, but I believe the problem is setup in ADFS.
