### ISSUE TITLE
Response missing issuer fails but does not populate errors

### ISSUE THREAD

**Issue by vincentwoo** [onelogin/ruby-saml#479]
I have a SAMLResponse object with the following interesting properties:

```
[32] pry(main)> response.success?
false
[33] pry(main)> response.errors
[]
[34] pry(main)> response.status_code
"urn:oasis:names:tc:SAML:2.0:status:Requester | "
[35] pry(main)> response.status_message
""
```

which isn't super helpful with diagnosing the real problem, which you only hit when doing this:

```
[38] pry(main)> response.issuers
OneLogin::RubySaml::ValidationError: Issuer of the Assertion not found or multiple.
from /app/vendor/bundle/ruby/2.5.0/gems/ruby-saml-1.9.0/lib/onelogin/ruby-saml/response.rb:295:in `issuers'
```

The response that triggered this looks like this (with some redactions):

```xml
<?xml version="1.0"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="https://coderpad.io/saml/acs" ID="A7d458dba-6bfe-409c-9f22-907f4a04ed18" InResponseTo="_882b52ec-3101-4873-8d86-892424db6dd9" IssueInstant="2018-11-16T22:03:36Z" Version="2.0">
  <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">REDACTED</saml:Issuer>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/>
      <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <Reference URI="#A7d458dba-6bfe-409c-9f22-907f4a04ed18">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <DigestValue>REDACTED</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>REDACTED</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509Certificate>REDACTED</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester"/>
    <samlp:StatusMessage Value="Authrequest expired"/>
  </samlp:Status>
</samlp:Response>
```

This seems wrong in that I'd a) expect `errors` to be populated on response creation and b) the status message to be populated.

**Comment by pitbulk** [comment]
When the Status Code of the SAMLResponse is Requester, that means that the IdP rejected the AuthNRequest.

You are right, and the StatusMessage should be shown, as is done in other toolkits, like [php.saml](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L462).

I will work on a PR to provide more info.

**Comment by pitbulk** [comment]
I think I found the issue.

The StatusCode has the following format:
```
 <samlp:StatusCode Value="http://www.example.com/">
</samlp:StatusCode>
```

but the StatusMessage has the following format:
```
<samlp:StatusMessage>string</samlp:StatusMessage>
```

So the [parser](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L240) fails to extract the Status Message of your Response.

**Comment by vincentwoo** [comment]
That's fine, but you'd still expect for an error to be set for a response that fails `is_valid?`

**Comment by pitbulk** [comment]
The [validate_success_status](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L390) method adds the error message.

So after executing is_valid? the reason should appear on the errors.

The issue is that you used response.success? instead response.is_valid?

response.success? only returns True or False if the response status is succes. Maybe that carry confusion and the method success? should originaly be named as has_success_status?
