### ISSUE TITLE
response.is_valid? is return false even though email-id is fetched

### ISSUE THREAD

**Issue by RohitVenturit** [onelogin/ruby-saml#480]
i am able to fetch email from SAMLResponse from attributes by this way: response.attributes["urn:oid:0.9.2342.19200300.100.1.3"]
but when I check response.is_valid? it return false. What could be reason? how to see error message?
response.errors returns me empty. Any bug here?

**Comment by pitbulk** [comment]
Check response.errors after calling response.is_valid?. The reason for the error should be at errors attribute.

**Comment by RohitVenturit** [comment]
As I said, response.errors is empty

**Comment by pitbulk** [comment]
@RohitVenturit, were you able to find the issue?

**Comment by trandinhchinh1995** [comment]
i have the same issue. response.errors is empty but response.is_valid? return false. I use idp gluu server. Can you help me explain this issue?

**Comment by pitbulk** [comment]
All validations defined on is_valid? append an error when the validation fails, you will need to debug the validate method and figure out what's going on.

**Comment by gdavila09** [comment]
I'm having the same issue response.errors empty but response.is_valid? false
