### ISSUE TITLE
validate_conditions not_before calculated wrong

### ISSUE THREAD

**Issue by pakwfoley** [onelogin/ruby-saml#481]
Currently the validation for the notbefore node is written as `(now + allowed_clock_drift) < not_before`. Since the current time `now` should be greater then notbefore minus the allowed drift: `now > not_before - allowed_clock_drift`. Adding `allowed clock` drift to both sides you get: `(now + allowed_clock_drift) > not_before`. So unless there's something I'm missing, I believe the inequality needs to be flipped.

**Comment by pakwfoley** [comment]
That is very confusing. So then the subject of `notBefore` is its own value? It's value cannot be before it's comparator?

**Comment by pitbulk** [comment]
The value of notBefore cant be less than now - allowed_clock_drift
