### ISSUE TITLE
Does not support idp multi certificates

### ISSUE THREAD

**Issue by raviiitb** [onelogin/ruby-saml#484]
I am trying to create a metadata XML file which supports both signing and encryption but seems it does not work.
I am adding this line into my settings 
```settings.idp_cert_multi = {:signing => [signing_pem], :encryption => [encryption_pem]}```
I am reading `signing_pem` and `encryption_pem`from a file.

It does not create x509 certificates in my metadata file
```xml
"<?xml version='1.0' encoding='UTF-8'?><md:EntityDescriptor ID='_bac0d4c5-7eb8-4dac-8910-001acde4e954' entityID='testentity' xmlns:md='urn:oasis:names:tc:SAML:2.0:metadata'><md:SPSSODescriptor AuthnRequestsSigned='true' WantAssertionsSigned='true' protocolSupportEnumeration='urn:oasis:names:tc:SAML:2.0:protocol'><md:SingleLogoutService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect' Location='https://example.com/auth/myex/slo' ResponseLocation='https://example.com/auth/myex/slo'/><md:AssertionConsumerService Binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' Location='https://example.com/auth/myex/callback' index='0' isDefault='true'/></md:SPSSODescriptor></md:EntityDescriptor>"
```

**Comment by patrickvinograd** [comment]
I believe you are setting the desired IdP signing and encryption certificates, but then you are examining the SP metadata. In other words, the IdP certs would not appear in the SP's metadata. Rather, you are configuring them in `settings` to be used internally upon receiving an assertion from the IdP.

**Comment by pitbulk** [comment]
Multi IdP cert are supported. 

See https://github.com/onelogin/ruby-saml#signature-validation
