### ISSUE TITLE
Decoding saml response with 509 certificate

### ISSUE THREAD

**Issue by vipulvkp** [onelogin/ruby-saml#487]
HI,

I have two rails application. Application 1 has been set as an Idp using saml-idp gem and Application 2 is the SP where I use this ruby-saml gem to consume and decode the saml body.

However from application 1, I am sending an encoded saml using a certificate. When I parse it on application 2, is_valid? returns false. I want to decode using the same certificate  so that is_valid? returns true. I have tried the below setting but is_valid still returns false.
def saml_settings
    settings = OneLogin::RubySaml::Settings.new
    settings.idp_cert = File.read("server.cert")
    settings.assertion_consumer_service_url = "https:/rails-application-2>/platform/index"
    settings.idp_cert_fingerprint_algorithm = "http://www.w3.org/2000/09/xmldsig#sha1"
    settings
end
Am I missing anything. Any further inputs will be appreciated.

**Comment by pitbulk** [comment]
After a call to is_valid, what data contains the errors attribute?
