### ISSUE TITLE
Blank logout request

### ISSUE THREAD

**Issue by prasunjit** [onelogin/ruby-saml#491]
During the IDP initiated logout flow, the `logout_request` object that I get from `OneLogin::RubySaml::SloLogoutrequest.new`  shows me invalid when I check `logout_request.is_valid ` and the error is `["Blank logout request"]` 

When I checked the `logout_request` object I could see the `@request` object is empty. 
Could you please explain if I am missing something here. I am getting the `LogoutRequest` from the IDP

**Comment by pitbulk** [comment]
"Blank logout request" means that the toolkit was not able to read the request object.

Are you providing the request to the SloLogoutrequest object?

See an example:
https://github.com/onelogin/ruby-saml-example/blob/master/app/controllers/saml_controller.rb#L110

**Comment by prasunjit** [comment]
Yes I am providing it but in a different way. Currently I am getting the SAMLRequest as part of the `post request body` So in stead of passing the params like below
`logout_request = OneLogin::RubySaml::SloLogoutrequest.new(params[:SAMLRequest], :settings => settings)`
I am passing it as below within double quotes
`logout_request = OneLogin::RubySaml::SloLogoutrequest.new("request.body.read", :settings => settings)`. 
Currently this does not throw `Blank request` but this looks confusing to me that I have to pass the `request.body.read` within a double quote. 

Is there any other way around  to pass the `request` object to the SloLogoutrequest  ?  We receive the SAMLrequest as part of `post` response from IDP as below 
```
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Envelope xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/">
  <ns0:Body>
    <ns0:LogoutRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Destination="xxxx" ID="xxxx" IssueInstant="2019-03-08T21:50:02Z" NotOnOrAfter="2019-03-08T22:00:02.431822+00:00" Version="2.0">
      <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">xxxxxxx</ns1:Issuer>
      <ns2:Signature Id="Signature1">
        <ns2:SignedInfo>
    </ns0:LogoutRequest>
  </ns0:Body>
</ns0:Envelope>
```

**Comment by pitbulk** [comment]
The ruby-saml toolkit only supports HTTP-Redirect binding for logouts.

If you pass the request in another way it's ok, but review that the toolkit gets what is expected.

**Comment by prasunjit** [comment]
Is the below xml format is what the toolkit is expecting ?
```
<ns0:LogoutRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Destination="xxxx" ID="xxxx" IssueInstant="2019-03-08T21:50:02Z" NotOnOrAfter="2019-03-08T22:00:02.431822+00:00" Version="2.0">
      <ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">xxxxxxx</ns1:Issuer>
      <ns2:Signature Id="Signature1">
        <ns2:SignedInfo>
</ns0:LogoutRequest>
```

**Comment by pitbulk** [comment]
The that should work, but I think the base64 encoded version of it.

**Comment by prasunjit** [comment]
Ok so the XML format has to be converted to base64 version. thanks for the clarification. 
This worked for me actually. Thanks for the help.

This might not be the right place to ask below question
I am getting `["Current time is on or after NotOnOrAfter (2019-03-11 19:57:50 UTC >= 2019-03-08 21:49:16 +0000)"]`
My application is deployed in AWS and when I checked the logs I saw the time is 2019-03-11 19:57:50 +0000. 
The xml format has an element as `IssueInstant="2019-03-11T19:57:50Z" NotOnOrAfter="2019-03-11T20:07:50.446092+00:00"`

So I don't see a big time difference between aws and the IDP. Do you happen to know what might cause this big time difference ?

**Comment by prasunjit** [comment]
Thanks for the clarification. This worked for me.

This might not be right place for the below question.
I am getting below error
`["Current time is on or after NotOnOrAfter (2019-03-11 19:57:50 UTC >= 2019-03-08 21:49:16 +0000)"]`. 
My application is deployed in AWS. When I checked the logs in AWS, currently the time in logs shows `2019-03-11 19:57:50 +0000` and the Logoutrequest has the element as `IssueInstant="2019-03-11T19:57:50Z" NotOnOrAfter="2019-03-11T20:07:50.446092+00:00"`.  So there is not much time difference between the IDP and AWS.

Do you happen to know what might cause this big time difference ?
