### ISSUE TITLE
logout_response creating a wrong/escaped encoded string

### ISSUE THREAD

**Issue by prasunjit** [onelogin/ruby-saml#492]
I am receiving SAML Logout Request from the IdP and  I am replying with a SAML Logout Response to the IdP

The below line successfully created a logout_request for me
`logout_request = OneLogin::RubySaml::SloLogoutrequest.new(params[:SAMLRequest])`

I was also able to create the logout response successfully from below 
`logout_response = OneLogin::RubySaml::SloLogoutresponse.new.create(saml_settings, logout_request_id, nil,)`

It logged me the below xml 
```
<samlp:LogoutResponse xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="xxxx" ID="xxxxx" InResponseTo=xxxxx" IssueInstant="xxxxx" Version="2.0">
  <saml:Issuer>xxxxxx</saml:Issuer>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    <samlp:StatusMessage>Successfully Signed Out</samlp:StatusMessage>
  </samlp:Status>
</samlp:LogoutResponse>
```
But it creates a different base 64 and deflated value like below . For example
`Redirected to https://somelogouturl.com&SAMLResponse=fZJNb9swDIb%2Fik%2FTybHrfNTR4gzdAmw`

But it should be `Redirected to https://somelogouturl.com&SAMLResponse=fVJNb9swDL0P2H8wdNjNsRMn`

I am getting the correct encoded value after decoding the xml file above from [here](https://www.samltool.com/encode.php)

I am using Rails 5.2.2 and Ruby 2.5.3 and ruby-saml -1.9.0

Could you please explain why the  `logout_response` is creating a different or escaped string
If it is also possible to just get the `LogoutResponse` xml string from ruby-saml libraray ? I can then convert the xml string to base 64 encoded value on my own

**Comment by pitbulk** [comment]
A simple white space or tab will make that the generated encoded SAMLResponse changes, that why you see different values because one of them is formatted and the other not.

**Comment by pitbulk** [comment]
The [create_xml_document](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/slo_logoutresponse.rb#L104) method will return the doc.
