### ISSUE TITLE
digest doesn't match unless C14N EXCLUSIVE is used for canonicalization

### ISSUE THREAD

**Issue by douglasrw** [onelogin/ruby-saml#496]
I'm trying to validate a  `SAMLRequest`, but   I get the error "digest mismatch".

In troubleshooting I notice that if I hack `ruby-saml` to use `Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0` just for the digest canon method then the `SMLRequest` DOES validate:

```
      # check digests
      ref = REXML::XPath.first(sig_element, "//ds:Reference", {"ds"=>DSIG})

      hashed_element = document.at_xpath("//*[@ID=$id]", nil, { 'id' => extract_signed_element_id })
      
     # HACK:  force EXCLUSIVE to troubleshoot
      canon_algorithm = Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0
      canon_hashed_element = hashed_element.canonicalize(canon_algorithm, inclusive_namespaces)
```

In the response the canonicalization method is specified as http://www.w3.org/TR/2001/REC-xml-c14n-20010315, which is used for the signature and and works:

```
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
```

I suspect there is a bug in `ruby-saml` b/c the same `SAMLResponse` validates using the online saml validation tool: https://www.samltool.com/validate_response.php

What could cause it to validate using the online tool, but fail with digest_match in ruby-saml ?

**Comment by pitbulk** [comment]
The online tool uses xmlseclibs that [calls](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/lib/Saml2/Utils.php#L1410) the [canonicalizeSignedInfo](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L670)
that uses the [canonicalizeData](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L633) methods that has as default method the ``http://www.w3.org/2001/10/xml-exc-c14n#WithComments``

I guess your SAMLResponse uses  that CanonicalizationMethod, that why when you harcoded
canon_algorithm = Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0 (that is http://www.w3.org/2001/10/xml-exc-c14n#WithComments), worked

But in ruby-saml,it [retrieves](https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L51
) Nokogiri::XML::XML_C14N_1_0 because
http://www.w3.org/TR/2001/REC-xml-c14n-20010315 was provided

I think something is wrong on the XML and in some situations the right value can't be retrieved, so the default is taken

**Comment by douglasrw** [comment]
> I guess your SAMLResponse uses that CanonicalizationMethod, that why when you harcoded
canon_algorithm = Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0 (that is http://www.w3.org/2001/10/xml-exc-c14n#WithComments), worked

@pitbulk - Interestingly, and this may not have been clear in my post, using `ruby-saml` the signature needs to use `Nokogiri::XML::XML_C14N_1_0` as the canon method, and the digest needs to use `Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0` for this response to validate

I wonder how the online saml validation tool swtiches between algos to validate the response, but `ruby-saml` doesn't for this particular response?

algo needed for signature:
```
      signature = Base64.decode64(OneLogin::RubySaml::Utils.element_text(base64_signature))
      # HACK: setting directly to illustrate the canon alg values that work to validate this response
      canon_algorithm = Nokogiri::XML::XML_C14N_1_0

      noko_sig_element = document.at_xpath('//ds:Signature', 'ds' => DSIG)
      noko_signed_info_element = noko_sig_element.at_xpath('./ds:SignedInfo', 'ds' => DSIG)

      canon_string = noko_signed_info_element.canonicalize(canon_algorithm)
```

then for the digest:

```
      # check digests
      ref = REXML::XPath.first(sig_element, "//ds:Reference", {"ds"=>DSIG})

      hashed_element = document.at_xpath("//*[@ID=$id]", nil, { 'id' => extract_signed_element_id })
      
     # HACK:  force EXCLUSIVE to validate the digest
      canon_algorithm = Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0
      canon_hashed_element = hashed_element.canonicalize(canon_algorithm, inclusive_namespaces)
```

**Comment by dphong1995** [comment]
@pitbulk @douglasrw The issue seems to come from the [Transforms element](https://www.w3.org/TR/xmldsig-core/#sec-Transforms). The online tool [process transform elements](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L858) before validating the digest value while ruby-saml doesn't. Hence, if the Transform element change the canon algorithm the digest check will fail.
Example:
```
<ds:SignedInfo>
  <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
  <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#IDd800a5e234004cbab63271826353b5f1">
    <ds:Transforms>
      <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
        <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"/>
      </ds:Transform>
    </ds:Transforms>
    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <ds:DigestValue>tKOm62Q4V/ONEFjnyMjP2hqHA70=</ds:DigestValue>
  </ds:Reference>
</ds:SignedInfo>
```

**Comment by pitbulk** [comment]
@dphong1995 I think that ruby-saml makes the same than php-saml

I reviewed how [PrefixList](https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L380) is calculated and how ruby-saml canonizes the [Signature](https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L313) and the [hashed element](https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L329).

What transformation process is missed?

**Comment by dphong1995** [comment]
@pitbulk 
I means [this process](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L730) is missed. As you can see, the `$data` variable is [calculated](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L858) based on hashed elements and transform elements. Then, the `$data` variable will be used to [validate the digest](https://github.com/onelogin/php-saml/blob/939f509143e95c21ab9720d2bfd5220c5828016d/extlib/xmlseclibs/xmlseclibs.php#L859) not the hashed elements. In other hand, `ruby-saml` will use the hashed elements without applying Transform elements to validate the digest which will result in the digest mismatch.

**Comment by douglasrw** [comment]
@dphong1995 / @pitbulk  - That does appear the issue here.   

The relevant elements for the response that's failing are below.  To get the digest check to validate I had to hack it to use `Nokogiri::XML::XML_C14N_EXCLUSIVE_1_0`, which is the correct method to use with `<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />`

```
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="#_c2d8f37a-0568-4c8a-933f-c77a9f4ea46c">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
          <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        </Transforms>
```

**Comment by pitbulk** [comment]
Can you verify that process_transforms solves the issue?

**Comment by douglasrw** [comment]
@pitbulk  - apologies for the late reply,  I ran a test locally and the process_transform branch _does_ fix the issue.  Big thanks.  I will provide the full response to test against.

**Comment by douglasrw** [comment]
@pitbulk - when can we expect this fix to be merged in?  Thanks, D

**Comment by robinator** [comment]
I've run the tests locally and it fixes the same issue I've been seeing as well.  Unfortunately my only test response _also_ has customer data in it 🤦‍♂️so It'll be tougher to supply an example.

**Comment by Capncavedan** [comment]
I encountered this issue recently, I see the PR has been merged - wondered if there's a new gem release planned anytime soon?
