### ISSUE TITLE
Is this gem support IDP side?

### ISSUE THREAD

**Issue by zty2developer** [onelogin/ruby-saml#501]
Is this gem only support SP side? I want to do the following steps(as a IDP)
1.handle saml request from SP
2.construct saml response and send it to SP

but I found that this gem has no way to handle saml request from SP.

It can just construct a saml response from a saml response param
```
response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], :settings => saml_settings)
```

**Comment by pitbulk** [comment]
It only supports SP.
