### ISSUE TITLE
Latest version do not set `sp_entity_id`

### ISSUE THREAD

**Issue by tknzk** [onelogin/ruby-saml#508]
```
-> % bundle exec rails c
Loading development environment (Rails 5.2.3)
[1] pry(main)> OneLogin::RubySaml::VERSION
=> "1.10.2"

[2] pry(main)> settings = OneLogin::RubySaml::Settings.new
=> #<OneLogin::RubySaml::Settings:0x00007fb966899e10
 @assertion_consumer_service_binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
 @attribute_consuming_service=#<OneLogin::RubySaml::AttributeService:0x00007fb966899ac8 @attributes=[], @index="1">,
 @compress_request=true,
 @compress_response=true,
 @double_quote_xml_attribute_values=false,
 @idp_cert_fingerprint_algorithm="http://www.w3.org/2000/09/xmldsig#sha1",
 @security=
  {:authn_requests_signed=>false,
   :logout_requests_signed=>false,
   :logout_responses_signed=>false,
   :want_assertions_signed=>false,
   :want_assertions_encrypted=>false,
   :want_name_id=>false,
   :metadata_signed=>false,
   :embed_sign=>false,
   :digest_method=>"http://www.w3.org/2000/09/xmldsig#sha1",
   :signature_method=>"http://www.w3.org/2000/09/xmldsig#rsa-sha1"},
 @single_logout_service_binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
 @soft=true>

[3] pry(main)> settings.sp_entity_id = "http://example.com/saml/metadata"
NoMethodError: undefined method `sp_entity_id=' for #<OneLogin::RubySaml::Settings:0x00007fb966899e10>
Did you mean?  idp_entity_id
from (pry):3:in `<main>'
```

Of course, using the old method (issuer =) is fine, but it seems to be deprecated, so I want to use the new method (sp_entity_id=).

**Comment by pitbulk** [comment]
The master branch has the [sp_entity_id method](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L89)

The latest version 1.10.2  was released on Apr 29, 2019 and lacks the sp_entity_id [commit](https://github.com/onelogin/ruby-saml/commit/660fc1071b59033d199ec9df6e0f8791b56c876b) that was introduced later.

You can use the master branch or apply directly the patch to the 1.10.2

There is no plan to release a new version of the ruby-saml toolkit soon.

**Comment by tknzk** [comment]
thanks.

It is understand if the message is written in the readme.
https://github.com/onelogin/ruby-saml#metadata-based-configuration 

We are waiting for a new version to be released.

**Comment by tknzk** [comment]
thanks release 1.11.0 
closed this issue.
