### ISSUE TITLE
Authentication failure! after setting skip_conditions to true

### ISSUE THREAD

**Issue by yoasyo25** [onelogin/ruby-saml#509]
We are using omniauth version 1.9.0 and omniauth-saml version 1.10.1 for SSO. We have been getting a lot of authentication errors and initially decided to increase the `allowed_clock_drift` to 30 seconds. As we continued to get validation errors, we decided to skip the validation for NotBefore by passing `skip_conditions: true` as a parameter. 

```
OneLogin::RubySaml::Response.new(params[:SAMLResponse], 
{ allowed_clock_drift: 30.seconds, skip_conditions: true })
```

But we are still seeing authentication failures.

```
Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, 
Current time is earlier than NotBefore condition 
(2019-06-27 14:01:21 UTC < 2019-06-27 14:01:42 UTC) 
```

Is there any other configuration we need to add? Does having `allowed_clock_drift` conflict with `skip_conditions` params?

Thanks!

**Comment by pitbulk** [comment]
I guess is a time sync issues on the machines involved (IdP and SP)
