### ISSUE TITLE
InResponseTo missing from SAML v2 response

### ISSUE THREAD

**Issue by albertsaave** [onelogin/ruby-saml#512]
Hi,

On the following picture, a successful login request is on the right, and the failing one is on the left. You can see that on the failing one, the inResponseTo attribute is missing. This is only happening for one okta user.

![image](https://user-images.githubusercontent.com/2468326/64831583-5cd00400-d5a4-11e9-9c61-bf0dcd649d01.png)

The error that I get is "Unsupported SAML version" which is thrown over here:
![image](https://user-images.githubusercontent.com/2468326/64831845-82114200-d5a5-11e9-92d0-3d68ce0c09c9.png)

 
Do you know why inResponseTo would be missing? What's the purpose of this attribute?

Thanks
Alberto

**Comment by pitbulk** [comment]
When the IdP initiates the SSO flow, then generates a SAMLResponse without the inResponseTo element, because is not replying to any AuthNrequest.

When the SP initiates the process, then the inResponseTo must match the AuthNRequest ID
