### ISSUE TITLE
Response Signature contains &#xd;

### ISSUE THREAD

**Issue by danielwheeler1987** [onelogin/ruby-saml#517]
Hello, I have a third party attempting to setup SSO with my organization. We are using your library... and it seems that the SAML response signature contains carriage returns and/or new lines. It doesn't seem like the validate_signature method takes this into consideration when attempting to handle the comparison.

Is this something that would be useful to add to the implementation... Or does it not behave this way on purpose. Thanks!

**Comment by danielwheeler1987** [comment]
Hey, Just checking in on this. I did some more testing and seems that the when validating the signature it doesn't event take new lines into consideration... and this seems to go against the SAML 2.0 spec.

**Comment by danielwheeler1987** [comment]
FYI... I have a PR I can push up that provides specs to show the issue I am discussing.

**Comment by pitbulk** [comment]
@danielwheeler1987 Please provide the PR and I will review.

**Comment by kingjason** [comment]
@danielwheeler1987 Hi Daniel - I'm running into a similar issue.  Were you able to resolve?

**Comment by darrylhopkins** [comment]
@kingjason , I'm a colleague of @danielwheeler1987 . We did resolve it on our end. I can try to find some code snippets of what we did in RoR if that would help you.

**Comment by darrylhopkins** [comment]
FYI, we found that this problem went away when we upgraded our ruby-saml gem. We were on v 1.7 and when we went to v 1.11, the problem went away. @kingjason
