### ISSUE TITLE
OneLogin::RubySaml::Response cannot locate issuer

### ISSUE THREAD

**Issue by liujohnson118** [onelogin/ruby-saml#522]
Hi, 

Appreciate the gem. But here is my trouble: 
Say I receive a logout SAMLResponse string: 
```
str ="fVJBTsMwEPxKbjm5iWPHcay2EoILEgiJIg5cqk3slEiOHWVtCX6P2wKiHHrc9ex4ZnbXCJOd1YM/+BieDc7eoclezYKjd5u8WpV5dn+3yfeCCtlRXZKh7YCUlDWk1qYhzcBZI+oBeCfy7GOyDtWJc5PHxSkPOKJyMBlUoVe7m8cHlUjVvPjge2//jlyfAESzhKQqz+4MhtFBOEl8D2FWRWF9D/bdY1CcM17EBMbiyFqMet7jeHD75DCZcT8uX3yyNeiGGgklqauSEQ6SkbaqNJF1W8s+MQnG0hBiNPcOA7iQQilpS2hFyvqFSlVxVdG3fLs+fqZOyGV7FIVJFczzyjtj/WF0q95PZ0WTCaAhQEGlMJp3LWm4kITLFK/kgpK+E0y0Q8e6elgXf4nX533tAoSIl9Wt12lzYKO5HiSe0GoX+94g5sUly2PqwcFsv5+HaO1ntkvxGZ09xXBW8x982f0tL69q+wU="
```

I was able to to `res = OneLogin::RubySaml::Response.new(str)` 

`res.response` would show up as a nice XML string of the successful logout response:
```
"<samlp:LogoutResponse Version='2.0' ID='_6168b1d0-f9ba-0137-5de7-7f43765fa4b6' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' Destination='http://localhost:4434/users/saml/idp_sign_out' InResponseTo='_fd71e8a0-5203-4a83-922d-85958c434633' IssueInstant='2019-12-05T18:24:21Z'><saml:Issuer>https://app.onelogin.com/saml/metadata/186ed4b9-7468-48d0-8461-cb6369fb3b5f</saml:Issuer><samlp:Status><samlp:StatusCode Value='urn:oasis:names:tc:SAML:2.0:status:Success'/><samlp:StatusMessage>Successfully Signed Out</samlp:StatusMessage></samlp:Status></samlp:LogoutResponse>"
```
In the XML, we can see the Issuer, which is https://app.onelogin.com/saml/metadata/186ed4b9-7468-48d0-8461-cb6369fb3b5f

But, as soon as I want to locate the issuer by `res.issuers`, I would get:
```
*** OneLogin::RubySaml::ValidationError Exception: Issuer of the Response not found or multiple.
```
The errors is an empty array [] too. 

Any suggestions? Thanks in advance!

**Comment by liujohnson118** [comment]
Just as a follow up, found this person's comment on devise_saml_authenticatable: https://github.com/apokalipto/devise_saml_authenticatable/issues/117#issuecomment-540826355

I tried his solution and it would work for me perfectly. However, I would like to know if there is an existing method in this gem that can do the same thing.

**Comment by pitbulk** [comment]
In order to read a LogoutRespponse you are using the wrong class.

Instead using OneLogin::RubySaml::Response, use OneLogin::RubySaml::[Logoutresponse](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/logoutresponse.rb#L12)
