### ISSUE TITLE
Is there a good way to implement the OneTimeUse condition?

### ISSUE THREAD

**Issue by bheeshmar** [onelogin/ruby-saml#527]
I have a client that wants us to respect the `OneTimeUse` condition for POST binding assertions to avoid replay attacks  as specified in 6.4.4 and 6.4.5 of the [SAML Security Considerations document](https://docs.oasis-open.org/security/saml/v2.0/saml-sec-consider-2.0-os.pdf).

> Countermeasures: Assertions communicated using this profile must always have short lifetimes and should have a `<OneTimeUse>` SAML assertion <Conditions> element. Service Provider sites are expected to ensure that the assertions are not re-used.

> Countermeasures: The profile mandates that the assertions transferred have the one-use property at the Service Provider site, preventing replay attacks from succeeding.

Any ideas how we might implement this? I don't believe it's currently checked in the gem.

The only idea I had involved monkey-patching response.rb to add the condition check and in it verify that an assertion with that ID doesn't exist in some cache that we maintain and if it doesn't add it to the cache.

**Comment by pitbulk** [comment]
when you process and valiate the SAMLResponse, save the response_id/assertion_id somewhere (for example database), then always check if the response_id exists or not on the database before take it as valid.

You only need to have this data saved a short period of time, the minutes the SAMLResponsse is valid.

You can extend the response class to return such response_id and assertion_id (similar to the php-saml implementation, for example: https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L222)

**Comment by kwerle** [comment]
Gosh, it'd sure be nice if that were built in (access to the ids).

**Comment by pitbulk** [comment]
I created https://github.com/onelogin/ruby-saml/issues/564  PRs welcome

**Comment by johnnyshields** [comment]
#564 is now resolved. Can this ticket be closed to? Should we add a note to the README?

**Comment by pitbulk** [comment]
Would be great to add it.

**Comment by Jmfwolf** [comment]
This issue has been resolved, I am closing it.
