### ISSUE TITLE
Option to enforce assertion encryption

### ISSUE THREAD

**Issue by irphilli** [onelogin/ruby-saml#528]
We have `want_assertions_encrypted` which includes key info in SP metadata.  It would be nice if that also enforced assertion encryption (or, maybe another option `require_assertions_encrypted`).  Similar to how it works for `want_assertions_signed`.

**Comment by JDrizzy** [comment]
Could you just drop the response or throw an error if the assertion is not encrypted? here's an example of what I'm currently doing https://github.com/onelogin/ruby-saml/issues/532

**Comment by irphilli** [comment]
Yes, that would work! Thanks for the suggestion! Will close this out.
