### ISSUE TITLE
How can multiple nameId formats be returned in the SP metadata xml?

### ISSUE THREAD

**Issue by synth** [onelogin/ruby-saml#530]
Consider the following non-onelogin publicly available metadata xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor entityID="nasdaq.zoom.us" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://nasdaq.zoom.us/saml/SingleLogout" ResponseLocation="https://nasdaq.zoom.us/saml/SingleLogout"/>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://nasdaq.zoom.us/saml/SingleLogout" ResponseLocation="https://nasdaq.zoom.us/saml/SingleLogout"/>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</md:NameIDFormat>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://nasdaq.zoom.us/saml/SSO" index="0" isDefault="true"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://nasdaq.zoom.us/saml/SSO" index="1"/></md:SPSSODescriptor>
</md:EntityDescriptor>
```

There are multiple nameId formats returned here. Is it possible for the OneLogin Ruby gem to have a saml configuration that returns similar metadata xml with multiple nameId formats?

The reason for asking is that we have a customer who has ADFS which is not working properly with our SP config. The error we get from the OneLogin gem is 
`The status code of the Response was not Success, was Requester => InvalidNameIDPolicy`

We have compared it against a working Zoom SSO config and the only difference between the two is that Zoom's SP metadata xml has multiple nameId formats - which seems to make sense given the error message.

I can certainly give more detail on the error and our specific situation, but I wanted to see if the multiple nameId formats was the culprit before diving deeper.

**Comment by pitbulk** [comment]
```
The status code of the Response was not Success, was Requester => InvalidNameIDPolicy
```
You need to review what NameID Format are supported on ADFS and set on settings the unspecified or one of the supported format, that way you avoid that error.

**Comment by synth** [comment]
@pitbulk We tried `unspecified` but that yielded other errors which I don't recall atm. We also tried many other possibilities of name format and attribute mapping on both sides. 

Is this gem capable of returning multiple nameId formats? From the code it doesn't seem possible, but seems like a good enhancement to account for situations like this. Clearly, other major SP's (eg Zoom) have the ability to return multiple nameId formats.

**Comment by pitbulk** [comment]
With this gem, the SP only publish 1 NameIdFormat on the Metadata.
That is the one that gonna be used on the AuthNRequest which only can carry 1 unique samlp:NameIDPolicy Format attribute.

You need to verify what NameId Format is accepted by the Idp you are trying to integrate and use the same Format that the IdP request. The value "unspecified" should work, no idea what error you experienced.

**Comment by synth** [comment]
Thanks @pitbulk. We tried unspecified and at first it didn't work. There are several types of unspecified formats actually. This is the one that worked for us with our customer's ADFS: `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified`
