### ISSUE TITLE
Metadata based configuration unexpectedly using fingerprint signature validation

### ISSUE THREAD

**Issue by clifff** [onelogin/ruby-saml#544]
I've been working on adding Okta login to a Rails app through SAML, using this gem. While reviewing this work, someone flagged this section of the README:

> In production also we highly recommend to register on the settings the IdP certificate instead of using the fingerprint method. The fingerprint, is a hash, so at the end is open to a collision attack that can end on a signature validation bypass. Other SAML toolkits deprecated that mechanism, we maintain it for compatibility and also to be used on test environment.

We are using `OneLogin::RubySaml::IdpMetadataParser` for configuration. Inspecting this configuration shows that `settings.get_idp_cert_multi` is `nil`, but `settings.get_idp_cert` is configured as expected.

To our surprise, this configuration results in `OneLogin::RubySaml::Response#validate_signature` only using the fingerprint for validation - not the actual certificate. This is because of two factors - `settings.get_idp_cert_multi` is `nil` here:

https://github.com/onelogin/ruby-saml/blob/63f43a7f9b830dfd690457a78a78fac48359944f/lib/onelogin/ruby-saml/response.rb#L844-L852

And that the document Okta is sending us includes a `X509Certificate` element that matches this query:

https://github.com/onelogin/ruby-saml/blob/63f43a7f9b830dfd690457a78a78fac48359944f/lib/xml_security.rb#L201-L209

In order to follow the recommendation against using the fingerprint method in production, we are setting `idp_cert_multi` manually to force `OneLogin::RubySaml::Response#validate_signature` into the branch that calls `validate_document_with_cert`. That code looks like this:

```ruby
response.settings.idp_cert_multi = {
  signing: [response.settings.get_idp_cert.to_pem]
}
if response.is_valid?
...
```

This behavior was unexpected so I wanted to flag it. I'm new to SAML so didn't want to assume a best path for fixing this, but I may be able to make a PR with a solution. Would either of these options make sense?

- Have `validate_signature` check against `settings.get_idp_cert` if available before using the fingerprint
- Have the metadata parser load a single available certificate into `idp_cert_multi`.

Let me know what sounds best.

**Comment by pitbulk** [comment]
Sorry for the delayed reply.

In the call
https://github.com/onelogin/ruby-saml/blob/12790136f03424fef7099a4379a03e88d5535af4/lib/onelogin/ruby-saml/response.rb#L856

If you have registered a cert in settings.certificate, then that cert will be registered on the command
https://github.com/onelogin/ruby-saml/blob/12790136f03424fef7099a4379a03e88d5535af4/lib/onelogin/ruby-saml/response.rb#L854
and past to the validate_document method.

In that method, if the SAMLResponse contains an x509certData, then its calculated fingerprint is compared with the calculated fingerprint registered in the settings

https://github.com/onelogin/ruby-saml/blob/449dd6b6a415e37c5cf8962e647f11a83021d6e2/lib/xml_security.rb#L225-L226

but check that the certificate used in
https://github.com/onelogin/ruby-saml/blob/449dd6b6a415e37c5cf8962e647f11a83021d6e2/lib/xml_security.rb#L241

is in fact the one registered on the settings
https://github.com/onelogin/ruby-saml/blob/449dd6b6a415e37c5cf8962e647f11a83021d6e2/lib/xml_security.rb#L232

**Comment by clifff** [comment]
Sorry for never getting back to this - I'd need to spend a while tracing code paths before any of it makes sense again. If it's helpful, one of my coworkers did come up with a failing test for this situation that may be clearer:

```diff
diff --git a/test/xml_security_test.rb b/test/xml_security_test.rb
index 3d3e758..6c77bd0 100644
--- a/test/xml_security_test.rb
+++ b/test/xml_security_test.rb
@@ -392,6 +392,36 @@ class XmlSecurityTest < Minitest::Test
           assert document.name_id.nil?, 'Document should expose only signed, valid details'
         end
       end
+
+      describe 'a hash collision attack' do
+        # some random cert that isn't the one in the document
+        let(:idp_cert) { ruby_saml_cert2 }
+        let(:idp_cert_fingerprint) { "fingerprint" }
+        let(:document_data) { read_response('response_with_signed_message_and_assertion.xml') }
+        let(:malicious_document) { XMLSecurity::SignedDocument.new(document_data) }
+        let(:malicious_cert) {
+          OpenSSL::X509::Certificate.new(
+            Base64.decode64(
+              malicious_document.elements["//ds:X509Certificate"].text
+            )
+          )
+        }
+
+        it 'shouldnt validate' do
+          # confirm that the cert in the doc is *not* the IDP cert
+          refute_equal idp_cert.to_pem, malicious_cert.to_pem
+
+          # simulate hash collision
+          OpenSSL::Digest::SHA1.any_instance.stubs(:hexdigest).with(malicious_cert.to_der).returns(idp_cert_fingerprint)
+
+          exception = assert_raises(OneLogin::RubySaml::ValidationError) do
+            malicious_document.validate_document(idp_cert_fingerprint, false, :cert => idp_cert)
+          end
+
+          assert_equal("Key validation error", exception.message)
+          assert_includes document.errors, "Key validation error"
+        end
+      end
```
