### ISSUE TITLE
Key Rollover Using New Key & Certificate Combo

### ISSUE THREAD

**Issue by omgitsbillryan** [onelogin/ruby-saml#546]
### The Problem
I want to rollover to a new keypair combo where _both_ the key and cert are brand new. 

### Extra Context
The wording for the ["Key Rollover" section](https://github.com/onelogin/ruby-saml#key-rollover) makes me think this is supported:

> If you plan to update the SP x509cert and **privateKey** you can define the parameter 'certificate_new' at the settings and that new SP public certificate will be published on the SP metadata so Identity Providers can read them and get ready for rollover.

...but I don't see any obvious settings for a new key (similar to what exists for the new cert, i.e. [`certificate_new`](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L59) )

### Other
I've successfully used this feature in the past. In that case, only the certificate was new; the private key remained the same. Is this feature only enabled for that use-case?

**Comment by omgitsbillryan** [comment]
Because code is always better, here is a workaround I came up with:

```ruby
# in the controller
LoginResponse.new(params[:SAMLResponse], settings: saml_settings)

# assumption: authnresponses are encrypted
class LoginResponse < OneLogin::RubySaml::Response
  def initialize(saml_response, options={})
    begin
      super(saml_response, options)
    rescue OpenSSL::PKey::RSAError => e # "padding check failed." when decrypt fails
      options[:settings].private_key = new_saml_key
      super(saml_response, options)
    end
  end
end
```

When the decrypt fails (because the IDP encrypted response with a new key), this is the stack trace:
```

**Comment by omgitsbillryan** [comment]
Mind the accidental closing of the issue ☝️ . Clicking buttons is hard.

**Comment by pitbulk** [comment]
Sorry for the delayed reply. 

The private_key never leaves the SP so you don't need to let the IdP know about a change on the private_key.

The certificate you can register on settings.certificate_new only gonna be used on the SP metadata, so the IdPs will be able to register on their side both, the old cert and the new cert.
Once the IdP has both certs, you can make the switch:  Removing the settings.certificate_new and then registering the new pair  x509cert and private key on settings.private_key and settings.certifiacte.

**Comment by omgitsbillryan** [comment]
Thanks for the response. Sorry for the even later reply.

Having to synchronize with the IdP is not ideal since it means downtime, even if only for a small number of seconds or minutes. 

Back when only our certificate changed (but still paired w/ the same private key), `ruby-saml` was able to seamlessly handle authn responses that were encrypted with _either_ `certificate` or `certificate_new`. This meant we could host the new certificate for a week or so, confirm that our IdP was using it, then assign `settings.certificate=<the new cert>` and remove `settings.certificate_new` entirely. Zero downtime.

It would be nice if we could follow this same zero downtime process in the event that the new certificate also has a new private key - say with a `private_key_new` `OneLogin::RubySaml::Settings` attr.

**Comment by s22su** [comment]
@pitbulk What are your thoughts about supporting multiple certificates and keys? Would something like this be worth a PR:

Add something like:
```ruby
settings.certificates = [{
  certificate: 'cert',
  key: 'key'
}]
```

1. When `settings.certificates` is present, publish all certificates in metadata
2. Allow IdP to use any certificate from that list (assuming IdP will use the most up-to-date one and it is not expired)
3. When validating the signature, could check against all the certificates in the list and consider it success when any of them matches + cert is not expired

It would simplify rollover a lot and to me, it seems very similar to how `idp_cert_multi` works right now. So we would bring similar functionality to SP side.

**Comment by pitbulk** [comment]
At php-saml we have the ability to:

[Register multiple IdP certs](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L128) for sign/encrypt
by the use of 
```
idp.x509certMulti
```

[Register a SP public](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L76) cert that gonna be used only to be published on the SP Metadata, so the IdP can register it from the SP Metadata, and once agreed on the change, execute the switch between x509cert and
```
x509certNew
```
equivalent to our [certificate_new](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L205)


Is your proposal to implement the equivalent to **idp.x509certMulti**?

So a settings.idp_certificates
