### ISSUE TITLE
Cut release + publish -- v1.11.1 

### ISSUE THREAD

**Issue by swordfish444** [onelogin/ruby-saml#549]
# Description

Adding this as an issue so it's top of mind. @pitbulk mentioned that this will be taking place soon in our conversation in #548 

![image](https://user-images.githubusercontent.com/3893966/95899587-a5c52f80-0d45-11eb-964f-050fcea9a41b.png)

Thank you for maintaining this library for the community!

**Comment by swordfish444** [comment]
@pitbulk @lawrencepit @olleolleolle 

What's the status on this? Would love to get a new release cut and gem bump.

**Comment by pitbulk** [comment]
Sorry for the delay.
I have some PRs and code pendingbut hope to make the release soon.

**Comment by kurko** [comment]
@pitbulk is there anything we could do to help with this release? We're relying on the `audience` patch, pointing directly at the `ref`, so it's risky and we'd like to help with the release in any way possible.

**Comment by pitbulk** [comment]
Working on it right now, sorry again for the delay

**Comment by fede-moya** [comment]
Hey there ! 👋🏼 , similar situation here, @pitbulk do you have an estimation of a date for the release ? Just to keep in mind. Thanks for maintaining this project.

**Comment by pitbulk** [comment]
I think the ETA is next week,

I still need to review & merge:
- https://github.com/onelogin/ruby-saml/pull/558
- https://github.com/onelogin/ruby-saml/pull/557
- https://github.com/onelogin/ruby-saml/pull/545
- https://github.com/onelogin/ruby-saml/pull/520

I'm working at the branch:
https://github.com/onelogin/ruby-saml/tree/1.12.0-dev

**Comment by fede-moya** [comment]
@pitbulk Thanks for the update ! 👏🏼

**Comment by pitbulk** [comment]
@fede-moya @kurko @swordfish444  1.12.0 branch will be released tomorrow.

Let me know if you find any issue on it.

**Comment by fede-moya** [comment]
@pitbulk Thank you sr ! 👏🏼 👏🏼 👏🏼

**Comment by pitbulk** [comment]
1.12.0 released
