### ISSUE TITLE
:assertion_consumer_service_binding not present in request to IdP

### ISSUE THREAD

**Issue by dan91** [onelogin/ruby-saml#554]
I set the :assertion_consumer_service_binding parameter to "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" using [omniauth-saml](https://github.com/omniauth/omniauth-saml). While the binding is present in the metadata xml, it is not included in the request.

With [saml-tracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) I inspected the request - there is no binding parameter:
`<samlp:AuthnRequest AssertionConsumerServiceURL="https://xxx.xx/users/auth/saml/callback"
                    Destination="https://idp.xxx.xx/idp/profile/SAML2/Redirect/SSO"
                    ID="_3e11f6d1-106e-4a25-b8f3-b887aa9bb576"
                    IssueInstant="2020-11-03T10:25:26Z"
                    Version="2.0"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    >
    <saml:Issuer>xxx</saml:Issuer>
</samlp:AuthnRequest>` 

This is the message I got from my IdP:
`2020-10-30 15:13:44,618 - xxx.xxx.xxx - WARN [net.shibboleth.idp.saml.profile.impl.PopulateBindingAndEndpointContexts:420] - Profile Action PopulateBindingAndEndpointContexts: Unable to resolve outbound message endpoint for relying party 'xxxx': EndpointCriterion [type={urn:oasis:names:tc:SAML:2.0:metadata}AssertionConsumerService, Location=https://xxxxx.xx/users/auth/saml/callback, trusted=false]`

Here is the my Devise config:
`Devise.setup do |config|
    config.omniauth :saml,
      :assertion_consumer_service_url => 'https://xxx.xx/users/auth/saml/callback',
      #:idp_cert_fingerprint => 'B7:BF:29:DA:3C:DE:4D:A1:0D:46:CC:7C:40:01:D1:96:22:86:BE:A3',
      :assertion_consumer_service_binding => "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
      :idp_cert                           => "-----BEGIN CERTIFICATE----- xxx-----END CERTIFICATE-----",
      :idp_sso_target_url => 'https://idp.xxx.xx/idp/profile/SAML2/Redirect/SSO',
      #:assertion_consumer_service_binding => "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
      :issuer                             => "xxx"`

**Comment by pitbulk** [comment]
The ProtocolBinding is an optional attribute of the AuthNRequest:
http://www.datypic.com/sc/saml2/e-samlp_AuthnRequest.html

The IdP should not require it.

```
ProtocolBinding [Optional]
A URI reference that identifies a SAML protocol binding to be used when returning the <Response>
message. See [SAMLBind] for more information about protocol bindings and URI references defined
for them. This attribute is mutually exclusive with the AssertionConsumerServiceIndex attribute
and is typically accompanied by the AssertionConsumerServiceURL attribute.
```
https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf

Are you sure you have registered properly the SP metadata, with the right SP Entity ID and ACS URL?
