### ISSUE TITLE
IdpMetadataParser doesn't read SLO ResponseLocation 

### ISSUE THREAD

**Issue by JCB-K** [onelogin/ruby-saml#556]
Hi! Ran into a similar issue as this one: https://github.com/onelogin/python3-saml/issues/13. Basically when parsing the following XML config `settings.idp_slo_target_url` will be set to `foo` rather than `bar`.

```xml
<ns0:SingleLogoutService
  Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
  Location="foo"
  ResponseLocation="bar"
/>
```

 Would you accept a PR that sets settings.idp_slo_target_url to the value on ResponseLocation if it's available? If so, are there cases where both the Location and ResponseLocation would need to be used?

Note: I'm not sure if me/my employer will be able to prioritise this, but wanted to check in first if a potential PR would be accepted.

Relevant code: https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/idp_metadata_parser.rb#L263-L273

**Comment by pitbulk** [comment]
We gonna need a new "single_logout_response_service_url" parameter to cover this scenario and the toolkit will need to use this instead single_logout_service_url when sending the LogoutResponse
