### ISSUE TITLE
Add interface to define validUntil/cacheDuration

### ISSUE THREAD

**Issue by nijel** [onelogin/ruby-saml#563]
The SAML medatada generated by ruby-saml violate the [SAML 2.0 specification](https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) because it doesn't include `validUntil` or `cacheDuration` attribute on the root `EntityDescriptor` element. It also doesn't provide an interface to define this by the application.

The specification is clear that it should be present at the root `EntityDescriptor` element.

> When used as the root element of a metadata instance, this element MUST contain either a validUntil or cacheDuration attribute.

Both `validUntil` and `cacheDuration` of the `EntityDescriptor` element are optional in the specification because they should appear only on the root element and are not recommended to use elsewhere and the `EntityDescriptor` element doesn't have to be a root element. 

Related issues:

* https://github.com/OTA-Insight/djangosaml2idp/issues/96 (lack of the required attributes lead to crash of the IDP)
* https://github.com/zammad/zammad/issues/3339

**Comment by pitbulk** [comment]
Will be available on 1.12.0
https://github.com/onelogin/ruby-saml/commit/92d6caf70e47f8e7218cb000b8fa9567eb2158cf
