### ISSUE TITLE
unsupported cipher algorithm (AES-128-GCM)

### ISSUE THREAD

**Issue by Kibe84** [onelogin/ruby-saml#569]
Hello, i updated ruby-saml version to 1.12.0, but still i get error unsupported cipher algorithm (AES-128-GCM).
I updated newest OPENSSL and i checked ciphers and looks like AES-128-GCM was found but it is written lowercase.
Is there upper/lower case issue or is there maybe some other problem?

**Comment by pitbulk** [comment]
I'm not aware of an upper/lower case issue.

If you replace [here](https://github.com/onelogin/ruby-saml/blob/bbd954b87c08e5e202dbaae9070f7e4aab8b45f8/lib/onelogin/ruby-saml/utils.rb#L294) the uppercase by lowercase, does it work for you then?

This thread refers to such upper/lower case issue as well:
https://stackoverflow.com/questions/24619503/ruby-unsupported-cipher-algorithm-aes-256-gcm

**Comment by Kibe84** [comment]
If i replace [here](https://github.com/onelogin/ruby-saml/blob/bbd954b87c08e5e202dbaae9070f7e4aab8b45f8/lib/onelogin/ruby-saml/utils.rb#L294) all AES-***-GCM with aes-***-gmc looks like it works after that update. After update it doesn't crash that unsupported algorithm.

**Comment by pitbulk** [comment]
I see, but can you confirm the way
```
OpenSSL::Cipher::AES.new(128, :GCM)
``` 
works as well?

**Comment by Kibe84** [comment]
I changed OpenSSL::Cipher.new('AES-128-GCM').decrypt -> OpenSSL::Cipher::AES.new(128, :GCM).decrypt and it looks like it works also.

**Comment by pitbulk** [comment]
ok, thanks for confirming
