### ISSUE TITLE
All xml invalid with 1.12.0

### ISSUE THREAD

**Issue by baelter** [onelogin/ruby-saml#571]
XML that worked with 1.11.0 is invalid with 1.12.0.
`settings.idp_sso_target_url` is now `nil` where it was set previously. 

Tried XML from Okta and Azure.

**Comment by baelter** [comment]
git blame tells me I should use `idp_sso_service_url` instead.

**Comment by pitbulk** [comment]
In that [commit](https://github.com/onelogin/ruby-saml/commit/6f8046ed9e8077beb882e1342c6a7283fc007286), I introduced the idp_sso_service_url and idp_slo_service_url

but if settings.idp_sso_service_url is not set, it should be used the value of settings.idp_sso_target_url
```
      def idp_sso_service_url
        val = nil
        if @idp_sso_service_url.nil?
          if @idp_sso_target_url
            val = @idp_sso_target_url
          end
        else
          val = @idp_sso_service_url
        end
        val
      end
```

how the parameters of your settings look like?

**Comment by zhuravel** [comment]
Have the same issue:
```ruby
IDP_METADATA = <<~XML
  <?xml version="1.0"?>
  <EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://app.onelogin.com/saml/metadata/100500">
    <IDPSSODescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <KeyDescriptor use="signing">
        <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
          <ds:X509Data>
            <ds:X509Certificate>MIICWDCCAcGgAwIBAgIBADANBgkqhkiG9w0BAQ0FADBIMQswCQYDVQQGEwJ1czET
  MBEGA1UECAwKQ2FsaWZvcm5pYTERMA8GA1UECgwIVGFsa2FibGUxETAPBgNVBAMM
  CFRhbGthYmxlMCAXDTE3MTAxODEwNTEwMloYDzIyOTIxMjE1MTA1MTAyWjBIMQsw
  CQYDVQQGEwJ1czETMBEGA1UECAwKQ2FsaWZvcm5pYTERMA8GA1UECgwIVGFsa2Fi
  bGUxETAPBgNVBAMMCFRhbGthYmxlMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB
  gQDSPK+387wuuvtUfboKA08upd/FGQk6raq8Z2XbJ898241e2plVrpayhd8yqxvI
  RZfgo+PKXDjctx71IG/nYE9sH1i0TwPsg0Darh/l9g+sevSE7XPGuXk+tSSAg31k
  bHm0u2fuKK9tKudJwVOC2M0NGiuIu4LJLSYtk1GUcGUhxQIDAQABo1AwTjAdBgNV
  HQ4EFgQUd94eOMal7K/1VZJL9EK8LAvmUIowHwYDVR0jBBgwFoAUd94eOMal7K/1
  VZJL9EK8LAvmUIowDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOBgQAzpO35
  AvCiikfh6OYTkSPRdAWwq6A7j1CWYAj9mjAnO/meR2/z6DUlmb4v5S2mKirwDoFc
  iUjIuk8Ja2PHUArYilDVMeH+Hmss+Eb3AYpPHTFqnvvlyKMdtSQJr9I34ozz68HA
  0TF5cOW11slBJwgIGDh+Nvw9bx62G3BWoAkSFw==</ds:X509Certificate>
          </ds:X509Data>
        </ds:KeyInfo>
      </KeyDescriptor>
      <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://talkable-dev.onelogin.com/trust/saml2/http-redirect/slo/100500"/>
      <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://talkable-dev.onelogin.com/trust/saml2/http-redirect/sso/100500"/>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://talkable-dev.onelogin.com/trust/saml2/http-post/sso/100500"/>
      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://talkable-dev.onelogin.com/trust/saml2/soap/sso/100500"/>
    </IDPSSODescriptor>
  </EntityDescriptor>
XML

parser = OneLogin::RubySaml::IdpMetadataParser.new
settings = parser.parse_to_hash(IDP_METADATA)
puts [OneLogin::RubySaml::VERSION, settings[:idp_sso_target_url]].inspect

=> ["1.11.0", "https://talkable-dev.onelogin.com/trust/saml2/http-redirect/sso/100500"]
=> ["1.12.0", nil]

**Comment by baelter** [comment]
> so the use of settings.idp_sso_target_url should still be compatible
> 
> how the parameters of your settings look like?

Seems to be a breaking change somewhere.

With `1.11.0` `idp_sso_target_url` was set, nothing else changes other than moving `ruby-saml` to `1.12.0` `idp_sso_target_url` is nil. (`idp_sso_service_url` returns the correct value though).

I guess the issue is you never set `idp_sso_target_url` when parsing (https://github.com/onelogin/ruby-saml/commit/6f8046ed9e8077beb882e1342c6a7283fc007286#diff-bb70d9aec12c5d4cf09ccead0b97fc3b31add1ad737d0eb5f1554079436be68bL213)

**Comment by pitbulk** [comment]
I gonna investigate

**Comment by pitbulk** [comment]
The parse_to_hash method now does not return the SSO URL inside the idp_sso_target_url and instead, returns it as idp_sso_service_url.

But the parse method that uses parse_to_hash will build the settings with this dict and initialize the Settings properly and the toolkit work as before, since now accepts IDP SSO URL endpoint value to be provided using idp_sso_target_url or idp_sso_service_url

@baelter, @zhuravel, @JCB-K  were you using directly parse_to_hash and then initializing the settings in a way that you were trying to retrieve directly the idp_sso_target_url index from the dict?

**Comment by baelter** [comment]
```
idp_metadata_parser = OneLogin::RubySaml::IdpMetadataParser.new
settings = idp_metadata_parser.parse saml_xml
settings.idp_sso_service_url.nil? # => false
settings. idp_sso_target_url.nil? # => true 
```

**Comment by pitbulk** [comment]
Yes, it fills idp_sso_service_url which is the parameter that will be used by the toolkit with preference over idp_sso_target_url

https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L79

**Comment by baelter** [comment]
Yea, so breaking change. behaviour of `idp_sso_target_url` changed.

**Comment by pitbulk** [comment]
The toolkit keeps working with the change, so I don't consider there was a behavior change at the toolkit level.

If you are using only the IdpMetadataParser class, I agree there was a behavior change and you need to use 
idp_sso_service_url and not idp_sso_target_url on 1.12.0

I could implement parse_to_hash to retrieve both, idp_sso_service_url and idp_sso_target_url, but that also opens the possible issue of having not the expected final value on the Settings, if a change is done after building the dict on idp_sso_target_url and not idp_sso_service_url which has preference.

**Comment by baelter** [comment]
Okey, all good. Closing this now that we have got it documented for others how run into this.

**Comment by webzorg** [comment]
This change wasn't mentioned in the changelog :S
