### ISSUE TITLE
Make max byte size configurable

### ISSUE THREAD

**Issue by dblessing** [onelogin/ruby-saml#598]
https://github.com/onelogin/ruby-saml/commit/533c84ebfc40f8cbac645b6c76ce4949f95d27d6 mitigated a vulnerability by creating a static max byte size (related to https://github.com/onelogin/ruby-saml/pull/383). We've encountered some cases where the SAML Response exceeds this size due to custom claims, such as when including groups a user is a member of. 

For this reason, it would be great if the max byte size was configurable. 

@pitbulk Do you think this would be a good feature?

**Comment by pitbulk** [comment]
What byte size has your SAMLResponse?

**Comment by dblessing** [comment]
@pitbulk In one case it looks like it was just less than .6MB. We believe some are even larger. 

If it's configurable then each instance can increase it if necessary - otherwise it remains the low .25MB default.
