### ISSUE TITLE
IdpMetadata#idp_cert_multi should always be assigned

### ISSUE THREAD

**Issue by johnnyshields** [onelogin/ruby-saml#604]
Currently `IdpMetadata#idp_cert_multi` is only assigned to a value when the IdP Metadata XML contains multiple unique certs. It would be useful for me if this variable were always assigned, so that I won't get different behavior for the 1 vs. N certificate cases.

**Comment by pitbulk** [comment]
I'm ok with such behavior change

**Comment by johnnyshields** [comment]
PR raised
