### ISSUE TITLE
Optional SubjectConfirmation

### ISSUE THREAD

**Issue by jzzsml** [onelogin/ruby-saml#624]
Hello!
When i add a `email@email.com` in the `saml_settings.name_identifier_value_requested` it will automatically generate subject field at auth request. 
But the saml:SubjectConfirmation field will also be generated in the request.

```
if settings.name_identifier_value_requested != nil
  subject = root.add_element "saml:Subject"

  nameid = subject.add_element "saml:NameID"
  nameid.attributes['Format'] = settings.name_identifier_format if settings.name_identifier_format
  nameid.text = settings.name_identifier_value_requested

  subject_confirmation = subject.add_element "saml:SubjectConfirmation"
  subject_confirmation.attributes['Method'] = "urn:oasis:names:tc:SAML:2.0:cm:bearer"
end
```

If I understood the [specification (4.1.4.1 <AuthnRequest> Usage)](http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf ) correctly, the field 'saml:SubjectConfirmation' is optional.

Is it possible to make this field optional at gem?

**Comment by pitbulk** [comment]
From the [SAML 2.0 core spec](https://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf)  Page 51

```
<saml:Subject> [Optional]
Specifies the requested subject of the resulting assertion(s). This may include one or more
<saml:SubjectConfirmation> elements to indicate how and/or by whom the resulting assertions
can be confirmed. For more information on this element, see Section 2.4.
If entirely omitted or if no identifier is included, the presenter of the message is presumed to be the
requested subject. If no <saml:SubjectConfirmation> elements are included, then the
presenter is presumed to be the only attesting entity required and the method is implied by the profile
of use and/or the policies of the identity provider
```

**Comment by jzzsml** [comment]
Thanks for the answer and for the links.
I still don't fully understand. Does the [new  SAML 2.0 core spec](https://www.oasis-open.org/committees/download.php/56776/sstc-saml-core-errata-2.0-wd-07.pdf) say that the <saml:SubjectConfirmation> may be missing?

> If no <saml:SubjectConfirmation> elements are included, then the
> presenter is presumed to be the only attesting entity required and the method is implied by the profile
> of use and/or the policies of the identity provider

**Comment by pitbulk** [comment]
It says the opposite:
```
Subject may include one or more <saml:SubjectConfirmation> elements to indicate how and/or by whom the resulting assertions can be confirmed
```

**Comment by jzzsml** [comment]
Ok. Thank You

**Comment by mt-dfrey** [comment]
Hi there!
I've been looking at this recently as well and also found this constraint on `<Subject>` nodes in the `<AuthnRequest>` of the Web SSO profile:

> Note that the service provider **MAY** include a `<Subject>` element in the request that names the actual identity about which it wishes to receive an assertion. This element **MUST NOT** contain any `<SubjectConfirmation>` elements. If the identity provider does not recognize the principal as that identity, then it **MUST** respond with a `<Response>` message containing an error status and no assertions.

source [Section 4.1.4.1 `<AuthnRequest>` Usage in the SAML profiles spec (including errata, 2015)](https://www.oasis-open.org/committees/download.php/56779/sstc-saml-bindings-errata-2.0-wd-06.pdf)

To me that sounds like the core spec allows `<SubjectConfirmation>` generally, but the Web SSO profile forbids it. Or am I missing something important here?
