### ISSUE TITLE
response.validate! call fails

### ISSUE THREAD

**Issue by eccegordo** [onelogin/ruby-saml#70]
Hi,

I am trying to use ruby-saml with a custom OmniAuth Strategy. I am using version 0.7.2
In my heroku logs I see

``` ruby
NoMethodError (undefined method `text' for nil:NilClass):
```

Below is what my OmniAuth callback phase looks like. The failure seems to be around the response.validate! call. Any thoughts on why this is happening? Problem in my code or in ruby-saml? I know I can receive the SAML response if I comment out that 

``` ruby
response.validate! 
```

call. But I am trying to understand the validate method. And specifically what steps I need to take to ensure the SAML assertion my application is receiving is properly signed and trustworthy.

``` ruby
      def callback_phase
        unless request.params['SAMLResponse']
          raise OmniAuth::Strategies::Company::ValidationError.new("SAML response missing")
        end

        response = Onelogin::Saml::Response.new(request.params['SAMLResponse'])
        response.settings = Onelogin::Saml::Settings.new(options)
        @name_id = response.name_id
        @attributes = response.attributes

        if @name_id.nil? || @name_id.empty?
          raise OmniAuth::Strategies::Company::ValidationError.new("SAML response missing 'name_id'")
        end
        response.validate!
        super
      rescue OmniAuth::Strategies::Company::ValidationError
        fail!(:invalid_ticket, $!)
      rescue Onelogin::Saml::ValidationError
        fail!(:invalid_ticket, $!)
      end

      uid { @name_id }
      info do
        {
            :company_id  => @attributes[:"CORP ID"],
            :name  => @attributes[:"Given Name"],
            :email  => @attributes[:"Email Address"],
            :account_type  => @attributes[:"Account Type"],
        }
      end
```

**Comment by tboyko** [comment]
> Try upgrading to 0.7.3 or higher if you are running into a similar issue.

@alperkokmen Typo? `0.7.2` is the most recent version available.

**Comment by alperkokmen** [comment]
@tboyko nope, [`0.7.3` was a release](https://github.com/onelogin/ruby-saml/releases/tag/0.7.3). It's fairly out-of-date at this point though. I would recommend using the latest version if you can.
