### ISSUE TITLE
Canonicalization in JRuby

### ISSUE THREAD

**Issue by jdewind** [onelogin/ruby-saml#77]
Nokogiri in JRuby does not appear to support canonicalization (https://github.com/sparklemotion/nokogiri/issues/226) properly such that it will create a digest mismatch. It doesn't appear there will be a fix immediately either since there hasn't been any action taken for 4 months. 

Unfortunately, the only work around would be to do a "soft" validation or explicitly remove the digest check in JRuby. :-(

See https://github.com/onelogin/ruby-saml/blob/master/lib/xml_security.rb#L92-L106

**Comment by snackycracky** [comment]
+1 for ruby-saml v0.8.1 with ruby-1.7.11
