### ISSUE TITLE
saml2:EncryptedAssertion

### ISSUE THREAD

**Issue by cmw** [onelogin/ruby-saml#9]
Hi,

the answer I get from the (Shibboleth) SAML 2 IdP I'm talking to is completely encoded and wrapped in a saml2:EncryptedAssertion element containing a certificate and two ciphers. Ruby-saml doesn't know how to handle this yet and I have not yet found out, how to handle it either.

Is anybody of you familiar with this type of response and perhaps already working on adding this to ruby-saml?

Also, any pointers are much appreciated so I can add it on my own.

Best,
Chris

**Comment by shyam-habarakada** [comment]
What is the status with the work in the decrypt branch? I am looking at it and noticing there hasn't been any new work for ~ 2 months.

**Comment by pitbulk** [comment]
The [decrypt branch](https://github.com/onelogin/ruby-saml/tree/decrypt) will be merged with some other features.

We still working on that merge and will publish a 1.0 release.

**Comment by shyam-habarakada** [comment]
I did use the decrypt branch to integrate with ADFS 2.0 (as the IdP) and was able to successfully enable encryption of the assertions. There were some issues I ran into around documentation and SAML standard compliance, which I have opened #186 to discuss. Thanks.

**Comment by samiljin** [comment]
I had the sam problem as @tekt8tket and his workaround helped. 
Could the 
```
assertion_plaintext.match(/(.*<\/(saml:|)Assertion>)/m)[0] 
``` 
be changed so it works with both, saml: and saml2:?

I think this would work:
```
assertion_plaintext.match(/(.*<\/(saml2*:|)Assertion>)/m)[0]
```

**Comment by pitbulk** [comment]
@samiljin, after merging this [239](https://github.com/onelogin/ruby-saml/pull/239) I will add official Encryption support.

I will take that suggestion in mind.

**Comment by rhomeister** [comment]
Is there a workaround in the meantime? I'm trying to integrate with a client that uses ADFS.

**Comment by pitbulk** [comment]
Try this branch:
https://github.com/onelogin/ruby-saml/tree/decrypt-support

**Comment by mohammedabualsoud** [comment]
I have same response, I wonder what is required for me as developer to extract the requested token in this case where the token is encrypted (I know that from the soap response has <EncryptedAssertion> tag).
Do I have to request a private key from the STS or what ?

Any help appreciated

**Comment by pitbulk** [comment]
Review [decrypt_assertion_from_document](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L893) method

**Comment by mohammedabualsoud** [comment]
@pitbulk I'm php developer. I don't understand what is the magic behind this statement decrypt_element(encrypted_assertion_node, /(.*<\/(\w+:)?Assertion>)/m)

the RSTR response message include EncryptedAssertion element within, this mean the token are encrypted right? I need a way to decry-pt it in order to use it to authenticate my application with another service provider.

Thanks

**Comment by pitbulk** [comment]
If you are a php developer.. then why you don't use [php-saml](https://github.com/onelogin/php-saml) instead of ruby-saml?

Review the [_decryptAssertion](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L800) method

**Comment by mohammedabualsoud** [comment]
@pitbulk can I use php-saml with machine to machine authentication (active authentication), I think not I'm using ws-trust with Bearer secenario

**Comment by pitbulk** [comment]
php-saml implement part of the SAML protocol. WS-Trust is a different protocol.

**Comment by mohammedabualsoud** [comment]
Exactly, but the format you got from ws-trust protocol are samel2 in my case.
and this lib mentioned it's for SSO in browser (with user interaction).
"SAML is an XML-based standard for web browser single sign-on"
